USE [master]
GO
/****** Object:  Database [OHBC_ASE_K21_LINE1]    Script Date: 2020/2/12 下午 02:25:01 ******/
CREATE DATABASE [OHBC_ASE_K21_LINE1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OHBC_ASE_K21_LINE1', FILENAME = N'D:\Microsoft_SQL\MSSQL14.MSSQLSERVER\MSSQL\DATA\OHBC_ASE_K21_LINE1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OHBC_ASE_K21_LINE1_log', FILENAME = N'D:\Microsoft_SQL\MSSQL14.MSSQLSERVER\MSSQL\DATA\OHBC_ASE_K21_LINE1_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OHBC_ASE_K21_LINE1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET ARITHABORT OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET  MULTI_USER 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET QUERY_STORE = OFF
GO
USE [OHBC_ASE_K21_LINE1]
GO
/****** Object:  Table [dbo].[ACMD_OHTC]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACMD_OHTC](
	[CMD_ID] [char](64) NOT NULL,
	[VH_ID] [char](32) NOT NULL,
	[CARRIER_ID] [char](64) NULL,
	[CMD_ID_MCS] [char](64) NULL,
	[CMD_TPYE] [int] NOT NULL,
	[SOURCE] [char](64) NULL,
	[DESTINATION] [char](64) NULL,
	[PRIORITY] [int] NOT NULL,
	[CMD_START_TIME] [datetime2](7) NULL,
	[CMD_END_TIME] [datetime2](7) NULL,
	[CMD_STAUS] [int] NOT NULL,
	[CMD_PROGRESS] [int] NOT NULL,
	[INTERRUPTED_REASON] [int] NULL,
	[ESTIMATED_TIME] [int] NOT NULL,
	[ESTIMATED_EXCESS_TIME] [int] NOT NULL,
	[REAL_CMP_TIME] [int] NULL,
	[SOURCE_ADR] [char](64) NULL,
	[DESTINATION_ADR] [char](64) NULL,
	[BOX_ID] [char](64) NULL,
	[LOT_ID] [char](64) NULL,
 CONSTRAINT [PK_ACMD_OHTC] PRIMARY KEY CLUSTERED 
(
	[CMD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACMD_MCS]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACMD_MCS](
	[CMD_ID] [varchar](64) NOT NULL,
	[CARRIER_ID] [varchar](64) NULL,
	[TRANSFERSTATE] [int] NOT NULL,
	[COMMANDSTATE] [int] NOT NULL,
	[HOSTSOURCE] [varchar](64) NULL,
	[HOSTDESTINATION] [varchar](64) NOT NULL,
	[PRIORITY] [int] NOT NULL,
	[CHECKCODE] [char](2) NOT NULL,
	[PAUSEFLAG] [char](1) NOT NULL,
	[CMD_INSER_TIME] [datetime2](7) NOT NULL,
	[CMD_START_TIME] [datetime2](7) NULL,
	[CMD_FINISH_TIME] [datetime2](7) NULL,
	[TIME_PRIORITY] [int] NOT NULL,
	[PORT_PRIORITY] [int] NOT NULL,
	[REPLACE] [int] NOT NULL,
	[PRIORITY_SUM] [int] NOT NULL,
	[BOX_ID] [varchar](64) NULL,
	[CARRIER_LOC] [varchar](64) NULL,
	[LOT_ID] [varchar](64) NOT NULL,
	[CARRIER_ID_ON_CRANE] [varchar](64) NULL,
	[CMDTYPE] [varchar](64) NULL,
 CONSTRAINT [PK_ACMD_MCS] PRIMARY KEY CLUSTERED 
(
	[CMD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VACMD_MCS]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VACMD_MCS]
AS
SELECT   m.CMD_ID, m.CARRIER_ID, m.TRANSFERSTATE, m.COMMANDSTATE, m.HOSTSOURCE, m.HOSTDESTINATION, m.PRIORITY_SUM, m.PRIORITY, m.CHECKCODE, m.PAUSEFLAG, m.CMD_INSER_TIME, 
              m.CMD_START_TIME, m.CMD_FINISH_TIME, m.TIME_PRIORITY, m.PORT_PRIORITY, m.REPLACE, o.CMD_ID AS OHTC_CMD, o.VH_ID
FROM     dbo.ACMD_MCS AS m LEFT OUTER JOIN
              dbo.ACMD_OHTC AS o ON m.CMD_ID = o.CMD_ID_MCS
GO
/****** Object:  Table [dbo].[ASECTION]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASECTION](
	[SEC_ID] [char](5) NOT NULL,
	[SEC_ORDER_NUM] [int] NULL,
	[SEG_ORDER_NUM] [int] NOT NULL,
	[DIRC_DRIV] [int] NOT NULL,
	[DIRC_GUID] [int] NOT NULL,
	[AREA_SECSOR] [int] NULL,
	[SEG_NUM] [char](3) NULL,
	[FROM_ADR_ID] [char](5) NULL,
	[TO_ADR_ID] [char](5) NULL,
	[SEC_DIS] [float] NOT NULL,
	[SEC_SPD] [float] NULL,
	[DIS_FROM_ORIGIN] [int] NOT NULL,
	[CDOG_1] [int] NOT NULL,
	[CHG_SEG_NUM_1] [char](3) NULL,
	[CDOG_2] [int] NOT NULL,
	[CHG_SEG_NUM_2] [char](3) NULL,
	[PRE_BLO_REQ] [int] NOT NULL,
	[SEC_TYPE] [int] NOT NULL,
	[SEC_DIR] [int] NOT NULL,
	[PADDING] [int] NOT NULL,
	[ENB_CHG_G_AREA] [int] NOT NULL,
	[PRE_DIV] [int] NOT NULL,
	[PRE_ADD_REPR] [int] NOT NULL,
	[OBS_SENSOR] [int] NOT NULL,
	[LAST_TECH_TIME] [datetime2](7) NULL,
	[SUB_VER] [char](4) NOT NULL,
	[ADD_TIME] [datetime2](7) NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime2](7) NULL,
	[UPD_USER] [char](10) NULL,
	[START_BC1] [int] NOT NULL,
	[END_BC1] [int] NOT NULL,
	[START_BC2] [int] NOT NULL,
	[END_BC2] [int] NOT NULL,
	[START_BC3] [int] NOT NULL,
	[END_BC3] [int] NOT NULL,
	[ADR1_CHG_SEC_ID_1] [char](5) NULL,
	[ADR1_CHG_SEC_COST_1] [int] NOT NULL,
	[ADR1_CHG_SEC_ID_2] [char](5) NULL,
	[ADR1_CHG_SEC_COST_2] [int] NOT NULL,
	[ADR1_CHG_SEC_ID_3] [char](5) NULL,
	[ADR1_CHG_SEC_COST_3] [int] NOT NULL,
	[ADR2_CHG_SEC_ID_1] [char](5) NULL,
	[ADR2_CHG_SEC_COST_1] [int] NOT NULL,
	[ADR2_CHG_SEC_ID_2] [char](5) NULL,
	[ADR2_CHG_SEC_COST_2] [int] NOT NULL,
	[ADR2_CHG_SEC_ID_3] [char](5) NULL,
	[ADR2_CHG_SEC_COST_3] [int] NOT NULL,
	[SEC_COST_From2To] [int] NOT NULL,
	[SEC_COST_To2From] [int] NOT NULL,
	[ISBANEND_From2To] [bit] NOT NULL,
	[ISBANEND_To2From] [bit] NOT NULL,
	[STATUS] [int] NOT NULL,
	[NOTE] [nchar](40) NULL,
	[PRE_DISABLE_FLAG] [bit] NOT NULL,
	[PRE_DISABLE_TIME] [datetime] NULL,
	[DISABLE_TIME] [datetime] NULL,
	[DISABLE_FLAG_USER] [bit] NOT NULL,
	[DISABLE_FLAG_SAFETY] [bit] NOT NULL,
	[DISABLE_FLAG_CHARGE] [bit] NOT NULL,
	[DISABLE_FLAG_SYSTEM] [bit] NOT NULL,
 CONSTRAINT [PK_ASECTION] PRIMARY KEY CLUSTERED 
(
	[SEC_ID] ASC,
	[SUB_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ASECTION_CONTROL_100]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASECTION_CONTROL_100](
	[SEC_ID] [char](5) NOT NULL,
	[CHG_AREA_SECSOR_1] [int] NOT NULL,
	[CHG_AREA_SECSOR_2] [int] NOT NULL,
	[OBS_SENSOR_F] [int] NOT NULL,
	[OBS_SENSOR_R] [int] NOT NULL,
	[OBS_SENSOR_L] [int] NOT NULL,
	[RANGE_SENSOR_F] [int] NOT NULL,
	[IS_ADR_RPT] [bit] NOT NULL,
	[CAN_GUIDE_CHG] [bit] NOT NULL,
	[HID_CONTROL] [bit] NOT NULL,
	[BRANCH_FLAG] [bit] NOT NULL,
	[SUB_VER] [char](4) NOT NULL,
	[ADD_TIME] [datetime2](7) NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime2](7) NULL,
	[UPD_USER] [char](10) NULL,
 CONSTRAINT [PK_SECTION_CONTROL_100] PRIMARY KEY CLUSTERED 
(
	[SEC_ID] ASC,
	[SUB_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VSECTION_100]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VSECTION_100]
AS
SELECT          dbo.ASECTION.SEC_ID, dbo.ASECTION.SEC_ORDER_NUM, dbo.ASECTION.SEG_ORDER_NUM, 
                            dbo.ASECTION.DIRC_DRIV, dbo.ASECTION.DIRC_GUID, dbo.ASECTION.SEG_NUM, dbo.ASECTION.FROM_ADR_ID, 
                            dbo.ASECTION.TO_ADR_ID, dbo.ASECTION.SEC_DIS, dbo.ASECTION.SEC_SPD, dbo.ASECTION.DIS_FROM_ORIGIN, 
                            dbo.ASECTION.CDOG_1, dbo.ASECTION.CHG_SEG_NUM_1, dbo.ASECTION.CDOG_2, 
                            dbo.ASECTION.CHG_SEG_NUM_2, dbo.ASECTION.PRE_BLO_REQ, dbo.ASECTION.SEC_TYPE, 
                            dbo.ASECTION.SEC_DIR, dbo.ASECTION.PADDING, dbo.ASECTION.ENB_CHG_G_AREA, dbo.ASECTION.PRE_DIV, 
                            dbo.ASECTION.PRE_ADD_REPR, dbo.ASECTION.OBS_SENSOR, dbo.ASECTION.SUB_VER, dbo.ASECTION.ADD_TIME, 
                            dbo.ASECTION.ADD_USER, dbo.ASECTION.UPD_TIME, dbo.ASECTION.UPD_USER, dbo.ASECTION.START_BC1, 
                            dbo.ASECTION.END_BC1, dbo.ASECTION.START_BC2, dbo.ASECTION.END_BC2, dbo.ASECTION.START_BC3, 
                            dbo.ASECTION.END_BC3, dbo.ASECTION_CONTROL_100.CHG_AREA_SECSOR_1, 
                            dbo.ASECTION_CONTROL_100.CHG_AREA_SECSOR_2, dbo.ASECTION_CONTROL_100.OBS_SENSOR_F, 
                            dbo.ASECTION_CONTROL_100.OBS_SENSOR_R, dbo.ASECTION_CONTROL_100.OBS_SENSOR_L, 
                            dbo.ASECTION_CONTROL_100.RANGE_SENSOR_F, dbo.ASECTION_CONTROL_100.IS_ADR_RPT, 
                            dbo.ASECTION_CONTROL_100.CAN_GUIDE_CHG, dbo.ASECTION_CONTROL_100.HID_CONTROL, 
                            dbo.ASECTION_CONTROL_100.BRANCH_FLAG, dbo.ASECTION.AREA_SECSOR, 
                            dbo.ASECTION.LAST_TECH_TIME
FROM              dbo.ASECTION INNER JOIN
                            dbo.ASECTION_CONTROL_100 ON dbo.ASECTION.SEC_ID = dbo.ASECTION_CONTROL_100.SEC_ID AND 
                            dbo.ASECTION.SUB_VER = dbo.ASECTION_CONTROL_100.SUB_VER
GO
/****** Object:  Table [dbo].[AADDRESS]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AADDRESS](
	[ADR_ID] [char](5) NOT NULL,
	[ADRTYPE] [int] NOT NULL,
	[SEC_ID] [char](5) NULL,
	[DISTANCE] [int] NULL,
	[CS_NUMBER] [char](10) NULL,
	[T_PULSE] [char](10) NULL,
	[P_LOCATION] [char](10) NOT NULL,
	[IS_DISPLAY] [int] NOT NULL,
	[ZOOM_LV] [int] NOT NULL,
	[BAR_CODE] [char](10) NULL,
	[OFFSET_X] [int] NOT NULL,
	[OFFSET_Y] [int] NOT NULL,
	[OFFSET_Z] [int] NOT NULL,
	[OFFSET_T] [int] NOT NULL,
	[PIO_ID] [char](6) NULL,
	[PIO_CHN] [int] NOT NULL,
	[PORT1_ID] [char](10) NULL,
	[P1_LD_VH_TYPE] [int] NOT NULL,
	[P1_ULD_VH_TYPE] [int] NOT NULL,
	[PORT2_ID] [char](10) NULL,
	[P2_LD_VH_TYPE] [int] NOT NULL,
	[P2_ULD_VH_TYPE] [int] NOT NULL,
 CONSTRAINT [PK_AADDRESS] PRIMARY KEY CLUSTERED 
(
	[ADR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AADDRESS_DATA]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AADDRESS_DATA](
	[ADR_ID] [char](5) NOT NULL,
	[VEHOCLE_ID] [char](5) NOT NULL,
	[RESOLUTION] [int] NOT NULL,
	[LOACTION] [int] NOT NULL,
 CONSTRAINT [PK_AADDRESS_DATA] PRIMARY KEY CLUSTERED 
(
	[ADR_ID] ASC,
	[VEHOCLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ABASEDATA_VER]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ABASEDATA_VER](
	[VER_TYPE] [int] NOT NULL,
	[SUB_VER] [char](4) NOT NULL,
	[REL_STAUS] [int] NULL,
	[ADD_TIME] [datetime] NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime] NULL,
	[UPD_USER] [char](10) NULL,
	[MEMO] [nchar](500) NULL,
 CONSTRAINT [PK_ABASEDATA_VER] PRIMARY KEY CLUSTERED 
(
	[VER_TYPE] ASC,
	[SUB_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ABLOCKZONEDETAIL]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ABLOCKZONEDETAIL](
	[ENTRY_SEC_ID] [nchar](5) NOT NULL,
	[SEC_ID] [nchar](5) NOT NULL,
 CONSTRAINT [PK_ABLOCKZONEDETAIL] PRIMARY KEY CLUSTERED 
(
	[SEC_ID] ASC,
	[ENTRY_SEC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ABLOCKZONEMASTER]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ABLOCKZONEMASTER](
	[ENTRY_SEC_ID] [char](5) NOT NULL,
	[BLOCK_ZONE_TYPE] [int] NOT NULL,
	[LEAVE_ADR_ID_1] [char](5) NOT NULL,
	[LEAVE_ADR_ID_2] [char](5) NOT NULL,
 CONSTRAINT [PK_ABLOCKZONEMASTER] PRIMARY KEY CLUSTERED 
(
	[ENTRY_SEC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ABUFFER]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ABUFFER](
	[BUFF_ID] [char](15) NOT NULL,
	[UNIT_NUM] [int] NOT NULL,
	[EQPT_ID] [char](15) NOT NULL,
	[CAPACITY] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BUFF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACASSETTE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACASSETTE](
	[CST_ID] [char](20) NOT NULL,
	[CST_STAT] [int] NOT NULL,
	[SHT_CNT] [int] NOT NULL,
	[PORT_ID] [char](15) NOT NULL,
	[CST_CODE] [char](1) NOT NULL,
	[LOT_ID] [char](20) NULL,
	[SLOT_MAP] [char](20) NOT NULL,
	[SLOT_SEL] [char](20) NULL,
	[END_STAT] [char](1) NOT NULL,
	[CRATE_ID] [char](20) NULL,
	[CSTLOGON_TIME] [datetime] NULL,
	[CSTLOGOff_TIME] [datetime] NULL,
	[ISLOTSTART] [char](1) NOT NULL,
	[CSTPROCSTART_TIME] [datetime] NULL,
	[CSTPROCEND_TIME] [datetime] NULL,
	[ROUNTINMODE] [char](1) NULL,
 CONSTRAINT [PK__ACASSETT__C92BBCB5C398589D] PRIMARY KEY CLUSTERED 
(
	[CST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACEID]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACEID](
	[CEID] [char](3) NOT NULL,
	[RPTID] [char](3) NOT NULL,
	[ORDER_NUM] [int] NOT NULL,
	[NAME] [char](20) NULL,
	[UPD_TIME] [datetime] NULL,
 CONSTRAINT [PK_ACEID] PRIMARY KEY CLUSTERED 
(
	[CEID] ASC,
	[RPTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACMD_OHTC_DETAIL]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACMD_OHTC_DETAIL](
	[CMD_ID] [char](64) NOT NULL,
	[SEQ_NO] [int] NOT NULL,
	[ADD_ID] [char](5) NOT NULL,
	[ADD_ENTRY_TIME] [datetime2](7) NULL,
	[SEC_ID] [char](10) NOT NULL,
	[SEG_NUM] [char](10) NOT NULL,
	[SEC_ENTRY_TIME] [datetime2](7) NULL,
	[SEC_LEAVE_TIME] [datetime2](7) NULL,
	[LOAD_START_TIME] [datetime2](7) NULL,
	[LOAD_END_TIME] [datetime2](7) NULL,
	[UNLOAD_START_TIME] [datetime2](7) NULL,
	[UNLOAD_END_TIME] [datetime2](7) NULL,
	[ESTIMATED_TIME] [int] NOT NULL,
	[IS_PASS] [bit] NOT NULL,
 CONSTRAINT [PK_ACMD_OHTC_DETAL] PRIMARY KEY CLUSTERED 
(
	[CMD_ID] ASC,
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACRATE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACRATE](
	[CRATE_ID] [char](20) NOT NULL,
	[MAKER] [char](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[CRATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACYCLEZONEDETAIL]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACYCLEZONEDETAIL](
	[CYCLE_ZONE_ID] [char](10) NOT NULL,
	[SEC_ID] [char](10) NOT NULL,
	[SEC_ORDER] [int] NOT NULL,
 CONSTRAINT [PK_ACYCLEZONEDETAIL] PRIMARY KEY CLUSTERED 
(
	[CYCLE_ZONE_ID] ASC,
	[SEC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACYCLEZONEMASTER]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACYCLEZONEMASTER](
	[CYCLE_TYPE_ID] [char](10) NOT NULL,
	[CYCLE_ZONE_ID] [char](10) NOT NULL,
	[VEHICLE_TYPE] [int] NOT NULL,
	[ENTRY_ADR_ID] [char](5) NOT NULL,
	[TOTAL_BORDER] [int] NOT NULL,
 CONSTRAINT [PK_ACYCLEZONEMASTER] PRIMARY KEY CLUSTERED 
(
	[CYCLE_TYPE_ID] ASC,
	[CYCLE_ZONE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACYCLEZONETYPE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACYCLEZONETYPE](
	[CYCLE_TYPE_ID] [char](10) NOT NULL,
	[PROD_ID] [char](10) NULL,
	[TOTAL_BORDER] [int] NOT NULL,
	[IS_DEFAULT] [int] NOT NULL,
 CONSTRAINT [PK_ACYCLEZONETYPE] PRIMARY KEY CLUSTERED 
(
	[CYCLE_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AECDATAMAP]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AECDATAMAP](
	[ECID] [char](4) NOT NULL,
	[EQPT_REAL_ID] [char](15) NULL,
	[ECNAME] [char](40) NULL,
	[ECMIN] [char](10) NULL,
	[ECMAX] [char](10) NULL,
	[ECV] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AEQPT]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AEQPT](
	[EQPT_ID] [char](15) NOT NULL,
	[NODE_ID] [char](15) NOT NULL,
	[CIM_MODE] [char](1) NOT NULL,
	[OPER_MODE] [char](1) NOT NULL,
	[INLINE_MODE] [char](1) NOT NULL,
	[EQPT_STAT] [char](1) NOT NULL,
	[EQPT_PROC_STAT] [char](1) NOT NULL,
	[CR_RECIPE] [char](33) NULL,
	[MAX_SHT_CNT] [int] NULL,
	[MIN_SHT_CNT] [int] NULL,
	[ALARM_STAT] [char](1) NULL,
	[WARN_STAT] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[EQPT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AEVENTRPTCOND]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AEVENTRPTCOND](
	[CEID] [char](3) NOT NULL,
	[ENABLE_FLG] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AFLOW_REL]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AFLOW_REL](
	[UPSTREAM_ID] [char](10) NOT NULL,
	[DOWNSTREAM_ID] [char](10) NOT NULL,
	[FR_ID] [char](10) NOT NULL,
	[REL_TYPE] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UPSTREAM_ID] ASC,
	[DOWNSTREAM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[FR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[FR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AGROUPRAILS]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AGROUPRAILS](
	[SECTION_ID] [char](5) NOT NULL,
	[RAIL_ID] [char](5) NOT NULL,
	[RAIL_NO] [int] NULL,
	[DIR] [int] NOT NULL,
 CONSTRAINT [PK_AGROUPRAILS] PRIMARY KEY CLUSTERED 
(
	[SECTION_ID] ASC,
	[RAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AHIDZONEDETAIL]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AHIDZONEDETAIL](
	[ENTRY_SEC_ID] [char](5) NOT NULL,
	[SEC_ID] [char](5) NOT NULL,
 CONSTRAINT [PK_AHIDZONEDETAIL] PRIMARY KEY CLUSTERED 
(
	[ENTRY_SEC_ID] ASC,
	[SEC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AHIDZONEMASTER]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AHIDZONEMASTER](
	[ENTRY_SEC_ID] [char](5) NOT NULL,
	[LEAVE_ADR_ID_1] [char](5) NOT NULL,
	[LEAVE_ADR_ID_2] [char](5) NULL,
	[MAX_LOAD_COUNT] [int] NOT NULL,
 CONSTRAINT [PK_AHIDZONEMASTER] PRIMARY KEY CLUSTERED 
(
	[ENTRY_SEC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AHIDZONEQUEUE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AHIDZONEQUEUE](
	[ENTRY_SEC_ID] [char](5) NOT NULL,
	[VEHICLE_ID] [char](10) NOT NULL,
	[REQ_TIME] [datetime2](7) NOT NULL,
	[BLOCK_TIME] [datetime2](7) NULL,
	[THROU_TIME] [datetime2](7) NULL,
	[RELEASE_TIME] [datetime2](7) NULL,
	[STATUS] [int] NOT NULL,
	[IS_PASUE] [bit] NOT NULL,
 CONSTRAINT [PK_AHIDZONEQUEUE] PRIMARY KEY CLUSTERED 
(
	[ENTRY_SEC_ID] ASC,
	[VEHICLE_ID] ASC,
	[REQ_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ALARM]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALARM](
	[EQPT_ID] [char](15) NOT NULL,
	[UNIT_NUM] [int] NOT NULL,
	[RPT_DATE_TIME] [char](19) NOT NULL,
	[ALAM_CODE] [char](10) NOT NULL,
	[ALAM_LVL] [int] NOT NULL,
	[ALAM_STAT] [int] NOT NULL,
	[ALAM_DESC] [char](80) NULL,
	[ERROR_ID] [char](64) NULL,
	[UnitID] [varchar](2) NULL,
	[UnitState] [varchar](2) NULL,
 CONSTRAINT [PK__ALARM__8E7D9890671C1517] PRIMARY KEY CLUSTERED 
(
	[EQPT_ID] ASC,
	[UNIT_NUM] ASC,
	[RPT_DATE_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ALARMMAP]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALARMMAP](
	[EQPT_ID] [char](5) NOT NULL,
	[ALARM_ID] [char](10) NOT NULL,
	[ALARM_LVL] [int] NOT NULL,
	[ALARM_DESC] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ALARMRPTCOND]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALARMRPTCOND](
	[EQPT_ID] [char](15) NOT NULL,
	[ALAM_CODE] [char](10) NOT NULL,
	[ENABLE_FLG] [char](1) NOT NULL,
 CONSTRAINT [PK_ALARMRPTCOND] PRIMARY KEY CLUSTERED 
(
	[EQPT_ID] ASC,
	[ALAM_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ALINE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALINE](
	[LINE_ID] [char](15) NOT NULL,
	[HOST_MODE] [int] NOT NULL,
	[LINE_STAT] [int] NOT NULL,
 CONSTRAINT [PK__ALINE__CD13A075B8BD746B] PRIMARY KEY CLUSTERED 
(
	[LINE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ALOT]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALOT](
	[LOT_ID] [char](20) NOT NULL,
	[SHT_TYP] [char](1) NULL,
	[CST_OPER_MODE] [char](1) NOT NULL,
	[DUMMY_TYPE] [char](1) NOT NULL,
	[LOT_JUDGE] [char](1) NULL,
	[WORK_ORDER] [char](30) NULL,
	[PROC_STAT] [char](1) NULL,
	[LOT_START_PROC_TIME] [char](16) NULL,
	[LOT_END_PROC_TIME] [char](16) NULL,
	[PROC_SHT_CNT] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[LOT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AMAIN_VER]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AMAIN_VER](
	[VER_YEAR] [char](4) NULL,
	[VER_MON] [char](2) NULL,
	[VER_DAY] [char](2) NULL,
	[VER_HOUR] [char](2) NULL,
	[VER_MIN] [char](2) NULL,
	[MAIN_VER] [char](4) NOT NULL,
	[VER_STAUS] [int] NULL,
	[REL_STAUS] [int] NULL,
	[MEMO] [nchar](500) NULL,
	[ADD_TIME] [datetime2](7) NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime2](7) NULL,
	[UPD_USER] [char](10) NULL,
 CONSTRAINT [PK_AMAIN_VER] PRIMARY KEY CLUSTERED 
(
	[MAIN_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AMCSREPORTQUEUE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AMCSREPORTQUEUE](
	[ID] [uniqueidentifier] NOT NULL,
	[SERIALIZED_SXFY] [varbinary](max) NOT NULL,
	[INTER_TIME] [datetime2](7) NOT NULL,
	[REPORT_TIME] [datetime2](7) NULL,
	[STREAMFUNCTION_NAME] [varchar](50) NOT NULL,
	[STREAMFUNCTION_CEID] [char](5) NULL,
	[MCS_CMD_ID] [char](64) NULL,
	[VEHICLE_ID] [char](32) NULL,
	[PORT_ID] [char](64) NULL,
 CONSTRAINT [PK_AMCSREPORTQUEUE_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ANETWORKQUALITY]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANETWORKQUALITY](
	[VEICLE_ID] [char](32) NOT NULL,
	[ADR_ID] [char](5) NOT NULL,
	[SEC_ID] [char](5) NOT NULL,
	[ACC_SEC_DIST] [int] NOT NULL,
	[UPD_TIME] [datetime2](7) NOT NULL,
	[PING_TIME] [bigint] NOT NULL,
 CONSTRAINT [PK_NETWORKQUALITY] PRIMARY KEY CLUSTERED 
(
	[VEICLE_ID] ASC,
	[ADR_ID] ASC,
	[SEC_ID] ASC,
	[UPD_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ANODE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANODE](
	[NODE_ID] [char](15) NOT NULL,
	[ZONE_ID] [char](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NODE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APARKZONEDETAIL]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APARKZONEDETAIL](
	[PARK_ZONE_ID] [char](10) NOT NULL,
	[ADR_ID] [char](5) NOT NULL,
	[PRIO] [int] NOT NULL,
	[CAR_ID] [char](5) NULL,
 CONSTRAINT [PK_APACKZONEDETAIL] PRIMARY KEY CLUSTERED 
(
	[PARK_ZONE_ID] ASC,
	[ADR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APARKZONEMASTER]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APARKZONEMASTER](
	[PARK_TYPE_ID] [char](10) NOT NULL,
	[PARK_ZONE_ID] [char](10) NOT NULL,
	[VEHICLE_TYPE] [int] NOT NULL,
	[ENTRY_ADR_ID] [char](5) NOT NULL,
	[TOTAL_BORDER] [int] NOT NULL,
	[LOWER_BORDER] [int] NOT NULL,
	[PARK_TYPE] [int] NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_APACKZONEMASTER] PRIMARY KEY CLUSTERED 
(
	[PARK_TYPE_ID] ASC,
	[PARK_ZONE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APARKZONETYPE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APARKZONETYPE](
	[PARK_TYPE_ID] [char](10) NOT NULL,
	[PROD_ID] [char](10) NULL,
	[TOTAL_BORDER] [int] NOT NULL,
	[IS_DEFAULT] [int] NOT NULL,
 CONSTRAINT [PK_APACKZONETYPE] PRIMARY KEY CLUSTERED 
(
	[PARK_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APOINT]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APOINT](
	[POINT_ID] [char](5) NOT NULL,
	[ADR_ID] [char](5) NULL,
	[RAIL_ID] [char](5) NULL,
	[POINTTYPE] [int] NOT NULL,
	[LOCATIONX] [int] NOT NULL,
	[LOCATIONY] [int] NOT NULL,
	[HEIGHT] [float] NOT NULL,
	[WIDTH] [float] NOT NULL,
	[COLOR] [char](10) NOT NULL,
 CONSTRAINT [PK_APOINT] PRIMARY KEY CLUSTERED 
(
	[POINT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APORT]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APORT](
	[PORT_ID] [char](15) NOT NULL,
	[UNIT_NUM] [int] NOT NULL,
	[PORT_NUM] [int] NOT NULL,
	[EQPT_ID] [char](15) NOT NULL,
	[PORT_TYPE] [char](1) NOT NULL,
	[PORT_USE_TYPE] [char](2) NULL,
	[PORT_REAL_TYPE] [char](2) NULL,
	[CAPACITY] [int] NOT NULL,
	[PORT_STAT] [char](1) NOT NULL,
	[PORT_ENABLE] [char](1) NOT NULL,
	[TRS_MODE] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[PORT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APORT_POSITION_TEACHING_DATA]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APORT_POSITION_TEACHING_DATA](
	[PORT_ID] [char](10) NOT NULL,
	[VH_ID] [char](10) NOT NULL,
	[POSITION_OFFSET] [int] NOT NULL,
	[RESOLUTION] [int] NOT NULL,
	[SUB_VER] [char](4) NOT NULL,
	[ADD_TIME] [datetime2](7) NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime2](7) NULL,
	[UPD_USER] [char](10) NULL,
 CONSTRAINT [PK_APORT_POSITION_TEACHING_DATA] PRIMARY KEY CLUSTERED 
(
	[PORT_ID] ASC,
	[VH_ID] ASC,
	[SUB_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APORTICON]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APORTICON](
	[PORT_ID] [char](10) NOT NULL,
	[ADR_ID] [char](5) NOT NULL,
	[RAIL_ID] [char](5) NOT NULL,
	[ADRTYPE] [int] NOT NULL,
	[LOCATIONX] [int] NOT NULL,
	[LOCATIONY] [int] NOT NULL,
	[HEIGHT] [int] NOT NULL,
	[WIDTH] [int] NOT NULL,
	[COLOR] [char](10) NOT NULL,
 CONSTRAINT [PK_APORTICON] PRIMARY KEY CLUSTERED 
(
	[PORT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APORTSTATION]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APORTSTATION](
	[PORT_ID] [char](15) NOT NULL,
	[ADRTYPE] [int] NOT NULL,
	[ADR_ID] [char](5) NULL,
	[LD_VH_TYPE] [int] NOT NULL,
	[ULD_VH_TYPE] [int] NOT NULL,
	[PRIORITY] [int] NOT NULL,
	[PORT_TYPE] [int] NOT NULL,
	[PORT_STATUS] [int] NOT NULL,
	[PORT_DIR] [int] NOT NULL,
	[PORT_SERVICE_STATUS] [int] NOT NULL,
 CONSTRAINT [PK_APORT] PRIMARY KEY CLUSTERED 
(
	[PORT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ARAIL]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARAIL](
	[RAIL_ID] [char](5) NOT NULL,
	[RAILTYPE] [int] NOT NULL,
	[LOCATIONX] [int] NOT NULL,
	[LOCATIONY] [int] NOT NULL,
	[WIDTH] [float] NOT NULL,
	[LENGTH] [float] NOT NULL,
	[COLOR] [char](10) NULL,
 CONSTRAINT [PK_ARAIL] PRIMARY KEY CLUSTERED 
(
	[RAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ARPTID]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARPTID](
	[RPTID] [char](3) NOT NULL,
	[VID] [char](3) NOT NULL,
	[ORDER_NUM] [int] NOT NULL,
	[NAME] [char](20) NULL,
	[UPD_TIME] [datetime] NULL,
 CONSTRAINT [PK_ARPTID] PRIMARY KEY CLUSTERED 
(
	[RPTID] ASC,
	[VID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ASEGMENT]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASEGMENT](
	[SEG_NUM] [char](10) NOT NULL,
	[STATUS] [int] NOT NULL,
	[SEG_TYPE] [int] NOT NULL,
	[SPECIAL_MARK] [int] NULL,
	[RESERVE_FIELD] [char](40) NULL,
	[NOTE] [nchar](40) NULL,
	[DIR] [int] NOT NULL,
	[PRE_DISABLE_FLAG] [bit] NOT NULL,
	[PRE_DISABLE_TIME] [datetime] NULL,
	[DISABLE_TIME] [datetime] NULL,
	[DISABLE_FLAG_USER] [bit] NOT NULL,
	[DISABLE_FLAG_SAFETY] [bit] NOT NULL,
	[DISABLE_FLAG_HID] [bit] NOT NULL,
	[DISABLE_FLAG_SYSTEM] [bit] NOT NULL,
 CONSTRAINT [PK_ASEGMENT] PRIMARY KEY CLUSTERED 
(
	[SEG_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ASEQUENCE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASEQUENCE](
	[SEQ_NAME] [char](15) NOT NULL,
	[NXT_VAL] [bigint] NOT NULL,
 CONSTRAINT [PK_ASEQUENCE] PRIMARY KEY CLUSTERED 
(
	[SEQ_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ASHEET]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASHEET](
	[SHT_ID] [char](20) NOT NULL,
	[JOB_NO] [char](5) NOT NULL,
	[LOT_ID] [char](20) NOT NULL,
	[PROD_ID] [char](20) NULL,
	[SHT_STAT] [char](1) NULL,
	[SOURCE_CST_ID] [char](20) NULL,
	[SOURCE_SLOT_NO] [int] NOT NULL,
	[SOURCE_PORT_NO] [int] NOT NULL,
	[TARGET_CST_ID] [char](20) NULL,
	[TARGET_SLOT_NO] [int] NOT NULL,
	[TARGET_PORT_NO] [int] NOT NULL,
	[PROC_FLAG] [char](8) NULL,
	[SHT_JUDGE] [char](1) NULL,
	[SHT_GRADE] [char](1) NULL,
	[PROC_INFO] [char](8) NULL,
	[PPID] [char](40) NULL,
	[CRATE_ID] [char](20) NULL,
	[TAKE_OUT_STAT] [char](1) NULL,
	[NODE_ID] [char](15) NULL,
	[CST_ID] [char](20) NULL,
	[SLOT_NO] [int] NOT NULL,
	[TAKE_OUT_TIME] [char](16) NULL,
	[SCRAP_CODE] [char](5) NULL,
	[REASON_CODE] [char](5) NULL,
PRIMARY KEY CLUSTERED 
(
	[SHT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[JOB_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[JOB_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ASUB_VER]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASUB_VER](
	[MAIN_VER] [char](4) NOT NULL,
	[VER_TYPE] [int] NOT NULL,
	[SUB_VER] [char](4) NULL,
	[ADD_TIME] [datetime] NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime] NULL,
	[UPD_USER] [char](10) NULL,
 CONSTRAINT [PK_ASUB_VER] PRIMARY KEY CLUSTERED 
(
	[MAIN_VER] ASC,
	[VER_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ASYSEXCUTEQUALITY]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASYSEXCUTEQUALITY](
	[CMD_ID_MCS] [char](64) NOT NULL,
	[CMD_INSERT_TIME] [datetime2](7) NOT NULL,
	[CMD_START_TIME] [datetime2](7) NULL,
	[CMD_FINISH_TIME] [datetime2](7) NULL,
	[CMD_FINISH_STATUS] [int] NULL,
	[VH_ID] [char](32) NULL,
	[VH_START_SEC_ID] [char](5) NULL,
	[SOURCE_ADR] [char](64) NULL,
	[SEC_CNT_TO_SOURCE] [int] NOT NULL,
	[SEC_DIS_TO_SOURCE] [int] NOT NULL,
	[DESTINATION_ADR] [char](64) NULL,
	[SEC_CNT_TO_DESTN] [int] NOT NULL,
	[SEC_DIS_TO_DESTN] [int] NOT NULL,
	[CMDQUEUE_TIME] [float] NOT NULL,
	[MOVE_TO_SOURCE_TIME] [float] NOT NULL,
	[TOTAL_BLOCK_TIME_TO_SOURCE] [float] NOT NULL,
	[TOTAL_OCS_TIME_TO_SOURCE] [float] NOT NULL,
	[TOTAL_BLOCK_COUNT_TO_SOURCE] [int] NOT NULL,
	[TOTAL_OCS_COUNT_TO_SOURCE] [int] NOT NULL,
	[MOVE_TO_DESTN_TIME] [float] NOT NULL,
	[TOTAL_BLOCK_TIME_TO_DESTN] [float] NOT NULL,
	[TOTAL_OCS_TIME_TO_DESTN] [float] NOT NULL,
	[TOTAL_BLOCK_COUNT_TO_DESTN] [int] NOT NULL,
	[TOTAL_OCS_COUNT_TO_DESTN] [int] NOT NULL,
	[TOTALPAUSE_TIME] [float] NOT NULL,
	[CMD_TOTAL_EXCUTION_TIME] [float] NOT NULL,
	[TOTAL_ACT_VH_COUNT] [int] NOT NULL,
	[PARKING_VH_COUNT] [int] NOT NULL,
	[CYCLERUN_VH_COUNT] [int] NOT NULL,
	[TOTAL_IDLE_VH_COUNT] [int] NOT NULL,
 CONSTRAINT [PK_ASYSEXCUTEQUALITY] PRIMARY KEY CLUSTERED 
(
	[CMD_ID_MCS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ATRACEITEM]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATRACEITEM](
	[TRACE_ID] [char](2) NOT NULL,
	[SVID] [char](5) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRACE_ID] ASC,
	[SVID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ATRACESET]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATRACESET](
	[TRACE_ID] [char](2) NOT NULL,
	[SMP_PERIOD] [char](6) NULL,
	[SMP_PERIOD_SEC] [bigint] NOT NULL,
	[TOTAL_SMP_CNT] [int] NOT NULL,
	[SMP_CNT] [int] NOT NULL,
	[NX_SMP_TIME] [datetime] NOT NULL,
	[SMP_TIME] [datetime] NOT NULL,
 CONSTRAINT [PK__ATRACESE__78EE8E64D29A6C5F] PRIMARY KEY CLUSTERED 
(
	[TRACE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AUNIT]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUNIT](
	[UNIT_ID] [char](15) NOT NULL,
	[UNIT_NUM] [int] NOT NULL,
	[EQPT_ID] [char](15) NOT NULL,
	[UNIT_CATE] [char](1) NOT NULL,
	[EQPT_TYPE] [char](1) NOT NULL,
	[CAPACITY] [int] NOT NULL,
	[UNIT_STAT] [int] NOT NULL,
 CONSTRAINT [PK__AUNIT__4ED198153BE606CC] PRIMARY KEY CLUSTERED 
(
	[UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AVEHICLE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AVEHICLE](
	[VEHICLE_ID] [char](32) NOT NULL,
	[VEHICLE_TYPE] [int] NOT NULL,
	[CUR_ADR_ID] [char](5) NULL,
	[CUR_SEC_ID] [char](5) NULL,
	[SEC_ENTRY_TIME] [datetime2](7) NULL,
	[ACC_SEC_DIST] [float] NOT NULL,
	[MODE_STATUS] [int] NOT NULL,
	[ACT_STATUS] [int] NOT NULL,
	[MCS_CMD] [char](64) NULL,
	[OHTC_CMD] [char](64) NULL,
	[BLOCK_PAUSE] [int] NOT NULL,
	[CMD_PAUSE] [int] NOT NULL,
	[OBS_PAUSE] [int] NOT NULL,
	[HID_PAUSE] [int] NOT NULL,
	[ERROR] [int] NOT NULL,
	[EARTHQUAKE_PAUSE] [int] NOT NULL,
	[SAFETY_DOOR_PAUSE] [int] NOT NULL,
	[OHXC_OBS_PAUSE] [int] NOT NULL,
	[OHXC_BLOCK_PAUSE] [int] NOT NULL,
	[OBS_DIST] [int] NOT NULL,
	[HAS_CST] [int] NOT NULL,
	[CST_ID] [char](64) NULL,
	[UPD_TIME] [datetime2](7) NULL,
	[VEHICLE_ACC_DIST] [int] NOT NULL,
	[MANT_ACC_DIST] [int] NOT NULL,
	[MANT_DATE] [datetime2](7) NULL,
	[GRIP_COUNT] [int] NOT NULL,
	[GRIP_MANT_COUNT] [int] NOT NULL,
	[GRIP_MANT_DATE] [datetime2](7) NULL,
	[NODE_ADR] [char](5) NULL,
	[IS_PARKING] [bit] NOT NULL,
	[PARK_TIME] [datetime2](7) NULL,
	[PARK_ADR_ID] [char](5) NULL,
	[IS_CYCLING] [bit] NOT NULL,
	[CYCLERUN_TIME] [datetime2](7) NULL,
	[CYCLERUN_ID] [char](10) NULL,
	[IS_INSTALLED] [bit] NOT NULL,
	[INSTALLED_TIME] [datetime2](7) NULL,
	[REMOVED_TIME] [datetime2](7) NULL,
	[BOX_ID] [char](64) NULL,
	[LOT_ID] [char](64) NULL,
 CONSTRAINT [PK_AVEHICLE] PRIMARY KEY CLUSTERED 
(
	[VEHICLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AVEHICLE_CONTROL_100]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AVEHICLE_CONTROL_100](
	[VEHICLE_ID] [char](32) NOT NULL,
	[GUIDE_START_STOP_SPEED] [int] NOT NULL,
	[GUIDE_MAX_SPD] [int] NOT NULL,
	[GUIDE_ACCEL_DECCEL_TIME] [int] NOT NULL,
	[GUIDE_S_CURVE_RATE] [int] NOT NULL,
	[GUIDE_RUN_SPD] [int] NOT NULL,
	[GUIDE_MANUAL_HIGH_SPD] [int] NOT NULL,
	[GUIDE_MANUAL_LOW_SPD] [int] NOT NULL,
	[GUIDE_LF_LOCK_POSITION] [int] NOT NULL,
	[GUIDE_LB_LOCK_POSITION] [int] NOT NULL,
	[GUIDE_RF_LOCK_POSITION] [int] NOT NULL,
	[GUIDE_RB_LOCK_POSITION] [int] NOT NULL,
	[GUIDE_CHG_STABLE_TIME] [int] NOT NULL,
	[TRAVEL_RESOLUTION] [int] NOT NULL,
	[TRAVEL_START_STOP_SPEED] [int] NOT NULL,
	[TRAVEL_MAX_SPD] [int] NOT NULL,
	[TRAVEL_ACCEL_DECCEL_TIME] [int] NOT NULL,
	[TRAVEL_S_CURVE_RATE] [int] NOT NULL,
	[TRAVEL_HOME_DIR] [int] NOT NULL,
	[TRAVEL_HOME_SPD] [int] NOT NULL,
	[TRAVEL_KEEP_DIS_SPD] [int] NOT NULL,
	[TRAVEL_MANUAL_HIGH_SPD] [int] NOT NULL,
	[TRAVEL_MANUAL_LOW_SPD] [int] NOT NULL,
	[TRAVEL_TEACHING_SPD] [int] NOT NULL,
	[TRAVEL_TRAVEL_DIR] [int] NOT NULL,
	[TRAVEL_ENCODER_POLARITY] [int] NOT NULL,
	[TRAVEL_F_DIR_LIMIT] [int] NOT NULL,
	[TRAVEL_R_DIR_LIMIT] [int] NOT NULL,
	[TRAVEL_OBS_DETECT_LONG] [int] NOT NULL,
	[TRAVEL_OBS_DETECT_SHORT] [int] NOT NULL,
	[SUB_VER] [char](4) NOT NULL,
	[ADD_TIME] [datetime2](7) NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime2](7) NULL,
	[UPD_USER] [char](10) NULL,
 CONSTRAINT [PK_AVEHICLE_CONTROL_100] PRIMARY KEY CLUSTERED 
(
	[VEHICLE_ID] ASC,
	[SUB_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AVIDINFO]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AVIDINFO](
	[EQ_ID] [char](32) NOT NULL,
	[MCS_CARRIER_ID] [char](64) NULL,
	[CARRIER_ID] [char](64) NULL,
	[CARRIER_LOC] [char](64) NULL,
	[CARRIER_INSTALLED_TIME] [datetime] NULL,
	[COMMAND_ID] [char](64) NULL,
	[SOURCEPORT] [char](64) NULL,
	[DESTPORT] [char](64) NULL,
	[PRIORITY] [int] NOT NULL,
	[RESULT_CODE] [int] NOT NULL,
	[VEHICLE_STATE] [int] NOT NULL,
	[COMMAND_TYPE] [char](64) NULL,
	[ALARM_ID] [char](64) NULL,
	[ALARM_TEXT] [char](64) NULL,
	[UNIT_ID] [char](64) NULL,
	[PORT_ID] [char](64) NULL,
	[REPLACE] [int] NOT NULL,
 CONSTRAINT [PK_AVIDINFO] PRIMARY KEY CLUSTERED 
(
	[EQ_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AZONE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AZONE](
	[ZONE_ID] [char](15) NOT NULL,
	[LINE_ID] [char](15) NULL,
	[LOT_ID] [char](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ZONE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BCSTAT]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BCSTAT](
	[BC_ID] [char](10) NOT NULL,
	[CLOSE_MODE] [char](1) NOT NULL,
	[RUN_TIMESTAMP] [char](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[BC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BLOCKZONEQUEUE]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BLOCKZONEQUEUE](
	[ENTRY_SEC_ID] [nchar](5) NOT NULL,
	[CAR_ID] [nchar](10) NOT NULL,
	[REQ_TIME] [datetime2](7) NOT NULL,
	[BLOCK_TIME] [datetime2](7) NULL,
	[THROU_TIME] [datetime2](7) NULL,
	[RELEASE_TIME] [datetime2](7) NULL,
	[STATUS] [char](1) NULL,
 CONSTRAINT [PK_BLOCKZONEQUEUE] PRIMARY KEY CLUSTERED 
(
	[CAR_ID] ASC,
	[ENTRY_SEC_ID] ASC,
	[REQ_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CassetteData]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CassetteData](
	[StockerID] [varchar](64) NULL,
	[CSTID] [varchar](64) NULL,
	[BOXID] [varchar](64) NOT NULL,
	[Carrier_LOC] [varchar](64) NOT NULL,
	[Stage] [numeric](2, 0) NOT NULL,
	[CSTState] [numeric](1, 0) NOT NULL,
	[LotID] [varchar](64) NULL,
	[EmptyCST] [varchar](2) NULL,
	[CSTType] [varchar](2) NULL,
	[CSTInDT] [varchar](25) NULL,
	[StoreDT] [varchar](25) NULL,
	[WaitOutOPDT] [varchar](25) NULL,
	[WaitOutLPDT] [varchar](25) NULL,
	[TrnDT] [varchar](25) NULL,
	[ReadStatus] [varchar](64) NULL,
 CONSTRAINT [PK_CassetteData] PRIMARY KEY CLUSTERED 
(
	[BOXID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTROL_DATA]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTROL_DATA](
	[T1] [int] NOT NULL,
	[T2] [int] NOT NULL,
	[T3] [int] NOT NULL,
	[T4] [int] NOT NULL,
	[T5] [int] NOT NULL,
	[T6] [int] NOT NULL,
	[T7] [int] NOT NULL,
	[T8] [int] NOT NULL,
	[BLOCK_REQ_TIME_OUT] [int] NOT NULL,
	[SUB_VER] [char](4) NOT NULL,
	[ADD_TIME] [datetime2](7) NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime2](7) NULL,
	[UPD_USER] [char](10) NULL,
 CONSTRAINT [PK_CONTROL_DATA] PRIMARY KEY CLUSTERED 
(
	[SUB_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HASHEET]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HASHEET](
	[SEQ_NO] [nvarchar](255) NOT NULL,
	[T_STAMP] [char](19) NULL,
	[SHT_ID] [char](20) NULL,
	[JOB_NO] [char](5) NOT NULL,
	[LOT_ID] [char](20) NOT NULL,
	[PROD_ID] [char](20) NULL,
	[SHT_STAT] [char](1) NULL,
	[SOURCE_CST_ID] [char](20) NULL,
	[SOURCE_SLOT_NO] [int] NOT NULL,
	[SOURCE_PORT_NO] [int] NOT NULL,
	[TARGET_CST_ID] [char](20) NULL,
	[TARGET_SLOT_NO] [int] NOT NULL,
	[TARGET_PORT_NO] [int] NOT NULL,
	[PROC_FLAG] [char](8) NULL,
	[SHT_JUDGE] [char](1) NULL,
	[SHT_GRADE] [char](1) NULL,
	[PROC_INFO] [char](8) NULL,
	[PPID] [char](40) NULL,
	[CRATE_ID] [char](20) NULL,
	[TAKE_OUT_STAT] [char](1) NULL,
	[NODE_ID] [char](15) NULL,
	[CST_ID] [char](20) NULL,
	[SLOT_NO] [int] NOT NULL,
	[TAKE_OUT_TIME] [char](16) NULL,
	[SCRAP_CODE] [char](5) NULL,
	[REASON_CODE] [char](5) NULL,
PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[JOB_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[JOB_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOPERATION]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOPERATION](
	[SEQ_NO] [nvarchar](255) NOT NULL,
	[T_STAMP] [char](19) NULL,
	[USER_ID] [char](20) NULL,
	[FORM_NAME] [char](30) NULL,
	[ACTION] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PortDef]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PortDef](
	[StockerID] [varchar](64) NULL,
	[PLCPortID] [varchar](64) NOT NULL,
	[OHBName] [varchar](20) NULL,
	[State] [numeric](2, 0) NULL,
	[Stage] [numeric](2, 0) NULL,
	[AGVState] [numeric](2, 0) NULL,
	[UnitType] [varchar](20) NULL,
	[HostEQPortID] [varchar](64) NULL,
	[ShelfID] [varchar](7) NULL,
	[PortType] [numeric](2, 0) NULL,
	[PortTypeDef] [int] NULL,
	[PortLocationType] [numeric](2, 0) NULL,
	[PortTypeIndex] [numeric](2, 0) NULL,
	[SourceWeighted] [numeric](2, 0) NULL,
	[DestWeighted] [numeric](2, 0) NULL,
	[Direction] [numeric](1, 0) NULL,
	[Color] [numeric](6, 0) NULL,
	[TimeOutForAutoUD] [numeric](6, 0) NULL,
	[TimeOutForAutoInZone] [varchar](64) NULL,
	[AlternateToZone] [varchar](64) NULL,
	[Vehicles] [numeric](1, 0) NULL,
	[Floor] [numeric](1, 0) NULL,
	[IgnoreModeChange] [varchar](1) NULL,
	[ReportMCSFlag] [varchar](1) NULL,
	[ReportStage] [numeric](2, 0) NULL,
	[NetHStnNo] [numeric](2, 0) NULL,
	[AreaSensorStnNo] [numeric](2, 0) NULL,
	[Presenton_InsCST] [varchar](1) NULL,
	[Presentoff_DelCST] [varchar](1) NULL,
	[ToEQ] [varchar](64) NULL,
	[TrnDT] [varchar](20) NULL,
	[AlarmType] [numeric](2, 0) NULL,
	[ADR_ID] [char](5) NULL,
	[PortGroup] [int] NULL,
	[PRIORITY] [int] NULL,
 CONSTRAINT [PK_PortDef_1] PRIMARY KEY CLUSTERED 
(
	[PLCPortID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCALE_BASE_DATA]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCALE_BASE_DATA](
	[RESOLUTION] [int] NOT NULL,
	[INPOSITION_AREA] [int] NOT NULL,
	[INPOSITION_STABLE_TIME] [int] NOT NULL,
	[TOTAL_SCALE_PULSE] [int] NOT NULL,
	[SCALE_OFFSET] [int] NOT NULL,
	[SCALE_RESE_DIST] [int] NOT NULL,
	[READ_DIR] [int] NOT NULL,
	[SUB_VER] [char](4) NOT NULL,
	[ADD_TIME] [datetime2](7) NULL,
	[ADD_USER] [char](10) NULL,
	[UPD_TIME] [datetime2](7) NULL,
	[UPD_USER] [char](10) NULL,
 CONSTRAINT [PK_SCALE_BASE_DATA] PRIMARY KEY CLUSTERED 
(
	[SUB_VER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ShelfDef]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShelfDef](
	[StockerID] [varchar](64) NOT NULL,
	[ShelfID] [varchar](7) NOT NULL,
	[Stage] [numeric](2, 0) NOT NULL,
	[Bank_X] [varchar](2) NULL,
	[Bay_Y] [varchar](3) NULL,
	[Level_Z] [varchar](2) NULL,
	[LocateCraneNo] [numeric](2, 0) NULL,
	[ShelfType] [numeric](2, 0) NULL,
	[ShelfState] [varchar](1) NULL,
	[ZoneID] [varchar](64) NULL,
	[Enable] [varchar](1) NULL,
	[OldEnableSts] [varchar](1) NULL,
	[EmptyBlockFlag] [varchar](1) NULL,
	[HoldState] [numeric](1, 0) NULL,
	[BCRReadFlag] [varchar](1) NULL,
	[TransferTimes] [numeric](10, 0) NULL,
	[ChargeLoc] [varchar](1) NULL,
	[SelectPriority] [numeric](2, 0) NULL,
	[Remark] [varchar](100) NULL,
	[TrnDT] [varchar](25) NULL,
	[HandoffDirection] [numeric](1, 0) NULL,
	[ADR_ID] [char](5) NULL,
 CONSTRAINT [PK_ShelfDef_1] PRIMARY KEY CLUSTERED 
(
	[ShelfID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UASFNC]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UASFNC](
	[FUNC_CODE] [char](60) NOT NULL,
	[FUNC_NAME] [char](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[FUNC_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UASUFNC]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UASUFNC](
	[USER_GRP] [char](20) NOT NULL,
	[FUNC_CODE] [char](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_GRP] ASC,
	[FUNC_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UASUSR]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UASUSR](
	[USER_ID] [char](20) NOT NULL,
	[BADGE_NUMBER] [char](80) NULL,
	[USER_NAME] [char](30) NULL,
	[DISABLE_FLG] [char](1) NULL,
	[POWER_USER_FLG] [char](1) NULL,
	[ADMIN_FLG] [char](1) NULL,
	[USER_GRP] [char](20) NULL,
	[DEPARTMENT] [char](20) NULL,
	[PASSWD] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UASUSRGRP]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UASUSRGRP](
	[USER_GRP] [char](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_GRP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ZoneDef]    Script Date: 2020/2/12 下午 02:25:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ZoneDef](
	[StockerID] [varchar](64) NOT NULL,
	[ZoneID] [varchar](64) NOT NULL,
	[ZoneName] [varchar](100) NULL,
	[HighWaterMark] [numeric](5, 0) NULL,
	[LowWaterMark] [numeric](5, 0) NULL,
	[ZoneType] [numeric](2, 0) NULL,
	[InventoryCheck] [varchar](1) NULL,
	[Color] [varchar](15) NULL,
	[SourceWeighted] [numeric](2, 0) NULL,
	[DestWeighted] [numeric](2, 0) NULL,
	[Remark] [varchar](100) NULL,
	[TrnDT] [varchar](20) NULL,
 CONSTRAINT [PK_ZoneDef_1] PRIMARY KEY CLUSTERED 
(
	[ZoneID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_OFFSET_X]  DEFAULT ((0)) FOR [OFFSET_X]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_OFFSET_Y]  DEFAULT ((0)) FOR [OFFSET_Y]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_OFFSET_Z]  DEFAULT ((0)) FOR [OFFSET_Z]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_OFFSET_T]  DEFAULT ((0)) FOR [OFFSET_T]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_PIO_CHN]  DEFAULT ((0)) FOR [PIO_CHN]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_P1_LD_VH_TYPE]  DEFAULT ((0)) FOR [P1_LD_VH_TYPE]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_P1_ULD_VH_TYPE]  DEFAULT ((0)) FOR [P1_ULD_VH_TYPE]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_P2_LD_VH_TYPE_1]  DEFAULT ((0)) FOR [P2_LD_VH_TYPE]
GO
ALTER TABLE [dbo].[AADDRESS] ADD  CONSTRAINT [DF_AADDRESS_P2_ULD_VH_TYPE_1]  DEFAULT ((0)) FOR [P2_ULD_VH_TYPE]
GO
ALTER TABLE [dbo].[ACMD_MCS] ADD  CONSTRAINT [DF_ACMD_MCS_REPLACE_1]  DEFAULT ((0)) FOR [REPLACE]
GO
ALTER TABLE [dbo].[ACMD_MCS] ADD  CONSTRAINT [DF_ACMD_MCS_CMDTYPE]  DEFAULT ((0)) FOR [CMDTYPE]
GO
ALTER TABLE [dbo].[ACMD_OHTC_DETAIL] ADD  CONSTRAINT [DF_ACMD_OHTC_DETAIL_IS_PASS]  DEFAULT ((0)) FOR [IS_PASS]
GO
ALTER TABLE [dbo].[ACYCLEZONEMASTER] ADD  CONSTRAINT [DF_ACYCLEZONEMASTER_VEHICLE_TYPE]  DEFAULT ((0)) FOR [VEHICLE_TYPE]
GO
ALTER TABLE [dbo].[APARKZONEMASTER] ADD  CONSTRAINT [DF_APACKZONEMASTER_VEHICLE_TYPE_1]  DEFAULT ((0)) FOR [VEHICLE_TYPE]
GO
ALTER TABLE [dbo].[APARKZONEMASTER] ADD  CONSTRAINT [DF_APARKZONEMASTER_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[APORTSTATION] ADD  CONSTRAINT [DF_APORT_ADRTYPE]  DEFAULT ((0)) FOR [ADRTYPE]
GO
ALTER TABLE [dbo].[APORTSTATION] ADD  CONSTRAINT [DF_APORT_LD_VH_TYPE]  DEFAULT ((0)) FOR [LD_VH_TYPE]
GO
ALTER TABLE [dbo].[APORTSTATION] ADD  CONSTRAINT [DF_APORT_ULD_VH_TYPE]  DEFAULT ((0)) FOR [ULD_VH_TYPE]
GO
ALTER TABLE [dbo].[APORTSTATION] ADD  CONSTRAINT [DF_APORTSTATION_PORT_TPYE]  DEFAULT ((0)) FOR [PORT_TYPE]
GO
ALTER TABLE [dbo].[APORTSTATION] ADD  CONSTRAINT [DF_APORTSTATION_PORT_STATUS]  DEFAULT ((0)) FOR [PORT_STATUS]
GO
ALTER TABLE [dbo].[APORTSTATION] ADD  CONSTRAINT [DF_APORTSTATION_PORT_DIR]  DEFAULT ((0)) FOR [PORT_DIR]
GO
ALTER TABLE [dbo].[APORTSTATION] ADD  DEFAULT ((0)) FOR [PORT_SERVICE_STATUS]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_ADR1_CHG_SEC_COST_1]  DEFAULT ((0)) FOR [ADR1_CHG_SEC_COST_1]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_ADR1_CHG_SEC_COST_2]  DEFAULT ((0)) FOR [ADR1_CHG_SEC_COST_2]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_ADR1_CHG_SEC_COST_3]  DEFAULT ((0)) FOR [ADR1_CHG_SEC_COST_3]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_ADR2_CHG_SEC_COST_1]  DEFAULT ((0)) FOR [ADR2_CHG_SEC_COST_1]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_ADR2_CHG_SEC_COST_2]  DEFAULT ((0)) FOR [ADR2_CHG_SEC_COST_2]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_ADR2_CHG_SEC_COST_3]  DEFAULT ((0)) FOR [ADR2_CHG_SEC_COST_3]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_SEC_COST_From2To]  DEFAULT ((0)) FOR [SEC_COST_From2To]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_SEC_COST_To2From]  DEFAULT ((0)) FOR [SEC_COST_To2From]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_ISBANEND_From2To]  DEFAULT ((0)) FOR [ISBANEND_From2To]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_ISBANEND_To2From]  DEFAULT ((0)) FOR [ISBANEND_To2From]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_STATUS_1]  DEFAULT ((0)) FOR [STATUS]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_PRE_DISABLE_FLAG_1]  DEFAULT ((0)) FOR [PRE_DISABLE_FLAG]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_DISABLE_FLAG_USER_1]  DEFAULT ((0)) FOR [DISABLE_FLAG_USER]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_DISABLE_FLAG_SAFETY_1]  DEFAULT ((0)) FOR [DISABLE_FLAG_SAFETY]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_DISABLE_FLAG_CHARGE]  DEFAULT ((0)) FOR [DISABLE_FLAG_CHARGE]
GO
ALTER TABLE [dbo].[ASECTION] ADD  CONSTRAINT [DF_ASECTION_DISABLE_FLAG_SYSTEM_1]  DEFAULT ((0)) FOR [DISABLE_FLAG_SYSTEM]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_CHG_AREA_SECSOR_1]  DEFAULT ((0)) FOR [CHG_AREA_SECSOR_1]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_CHG_AREA_SECSOR_2]  DEFAULT ((0)) FOR [CHG_AREA_SECSOR_2]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_OBS_SENSOR_F]  DEFAULT ((0)) FOR [OBS_SENSOR_F]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_OBS_SENSOR_R]  DEFAULT ((0)) FOR [OBS_SENSOR_R]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_OBS_SENSOR_L]  DEFAULT ((0)) FOR [OBS_SENSOR_L]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_IS_ADR_RPT]  DEFAULT ((0)) FOR [IS_ADR_RPT]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_CAN_GUIDE_CHG]  DEFAULT ((0)) FOR [CAN_GUIDE_CHG]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_HID_CONTROL]  DEFAULT ((0)) FOR [HID_CONTROL]
GO
ALTER TABLE [dbo].[ASECTION_CONTROL_100] ADD  CONSTRAINT [DF_ASECTION_CONTROL_100_BRANCH_FLAG]  DEFAULT ((0)) FOR [BRANCH_FLAG]
GO
ALTER TABLE [dbo].[ASEGMENT] ADD  CONSTRAINT [DF_ASEGMENT_DISABLE_FLAG_USER]  DEFAULT ((0)) FOR [DISABLE_FLAG_USER]
GO
ALTER TABLE [dbo].[ASEGMENT] ADD  CONSTRAINT [DF_ASEGMENT_DISABLE_FLAG_SAFETY]  DEFAULT ((0)) FOR [DISABLE_FLAG_SAFETY]
GO
ALTER TABLE [dbo].[ASEGMENT] ADD  CONSTRAINT [DF_ASEGMENT_DISABLE_FLAG_HID]  DEFAULT ((0)) FOR [DISABLE_FLAG_HID]
GO
ALTER TABLE [dbo].[ASEGMENT] ADD  CONSTRAINT [DF_ASEGMENT_DISABLE_FLAG_SYSTEM]  DEFAULT ((0)) FOR [DISABLE_FLAG_SYSTEM]
GO
ALTER TABLE [dbo].[ASHEET] ADD  DEFAULT ((0)) FOR [PROC_FLAG]
GO
ALTER TABLE [dbo].[ASHEET] ADD  DEFAULT ((0)) FOR [PROC_INFO]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_SEC_CNT_TO_SOURCE]  DEFAULT ((0)) FOR [SEC_CNT_TO_SOURCE]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_SEC_DIS_TO_SOURCE]  DEFAULT ((0)) FOR [SEC_DIS_TO_SOURCE]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_SEC_CNT_TO_DESTN]  DEFAULT ((0)) FOR [SEC_CNT_TO_DESTN]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_SEC_DIS_TO_DESTN]  DEFAULT ((0)) FOR [SEC_DIS_TO_DESTN]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_OHTC_CMD_PROC_TIME]  DEFAULT ((0)) FOR [CMDQUEUE_TIME]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_MOVE_TO_SOURCE_TIME]  DEFAULT ((0)) FOR [MOVE_TO_SOURCE_TIME]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_BLOCK_TIME_TO_SOURCE]  DEFAULT ((0)) FOR [TOTAL_BLOCK_TIME_TO_SOURCE]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_OCS_TIME_TO_SOURCE]  DEFAULT ((0)) FOR [TOTAL_OCS_TIME_TO_SOURCE]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_BLOCK_COUNT_TO_SOURCE]  DEFAULT ((0)) FOR [TOTAL_BLOCK_COUNT_TO_SOURCE]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_OCS_COUNT_TO_SOURCE]  DEFAULT ((0)) FOR [TOTAL_OCS_COUNT_TO_SOURCE]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_MOVE_TO_DESTN_TIME]  DEFAULT ((0)) FOR [MOVE_TO_DESTN_TIME]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_BLOCK_TIME_TO_DESTN]  DEFAULT ((0)) FOR [TOTAL_BLOCK_TIME_TO_DESTN]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_OCS_TIME_TO_DESTN]  DEFAULT ((0)) FOR [TOTAL_OCS_TIME_TO_DESTN]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_BLOCK_COUNT_TO_DESTN]  DEFAULT ((0)) FOR [TOTAL_BLOCK_COUNT_TO_DESTN]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_OCS_COUNT_TO_DESTN]  DEFAULT ((0)) FOR [TOTAL_OCS_COUNT_TO_DESTN]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTALPAUSETIME]  DEFAULT ((0)) FOR [TOTALPAUSE_TIME]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_CMD_TOTAL_EXCUTION_TIME]  DEFAULT ((0)) FOR [CMD_TOTAL_EXCUTION_TIME]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_ACT_VH]  DEFAULT ((0)) FOR [TOTAL_ACT_VH_COUNT]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_PARKING_VH_COUNT]  DEFAULT ((0)) FOR [PARKING_VH_COUNT]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_CYCLERUN_VH_COUNT]  DEFAULT ((0)) FOR [CYCLERUN_VH_COUNT]
GO
ALTER TABLE [dbo].[ASYSEXCUTEQUALITY] ADD  CONSTRAINT [DF_ASYSEXCUTEQUALITY_TOTAL_IDLE_VH_COUNT]  DEFAULT ((0)) FOR [TOTAL_IDLE_VH_COUNT]
GO
ALTER TABLE [dbo].[AVEHICLE] ADD  CONSTRAINT [DF_AVEHICLE_VEHICLE_TYPE_1]  DEFAULT ((0)) FOR [VEHICLE_TYPE]
GO
ALTER TABLE [dbo].[AVEHICLE] ADD  CONSTRAINT [DF_AVEHICLE_EARTHQUAKE_PAUSE]  DEFAULT ((0)) FOR [EARTHQUAKE_PAUSE]
GO
ALTER TABLE [dbo].[AVEHICLE] ADD  CONSTRAINT [DF_AVEHICLE_SAFETY_DOOR_PAUSE]  DEFAULT ((0)) FOR [SAFETY_DOOR_PAUSE]
GO
ALTER TABLE [dbo].[AVEHICLE] ADD  CONSTRAINT [DF_AVEHICLE_OHXC_OBS_PAUSE]  DEFAULT ((0)) FOR [OHXC_OBS_PAUSE]
GO
ALTER TABLE [dbo].[AVEHICLE] ADD  CONSTRAINT [DF_AVEHICLE_OHXC_BLOCK_PAUSE]  DEFAULT ((0)) FOR [OHXC_BLOCK_PAUSE]
GO
ALTER TABLE [dbo].[AVEHICLE] ADD  CONSTRAINT [DF_AVEHICLE_IS_INSTALLED]  DEFAULT ((0)) FOR [IS_INSTALLED]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_START_STOP_SPEED]  DEFAULT ((0)) FOR [GUIDE_START_STOP_SPEED]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_MAX_SPD]  DEFAULT ((0)) FOR [GUIDE_MAX_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_ACCEL_DECCEL_TIME]  DEFAULT ((0)) FOR [GUIDE_ACCEL_DECCEL_TIME]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_S_CURVE_RATE]  DEFAULT ((0)) FOR [GUIDE_S_CURVE_RATE]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_RUN_SPD]  DEFAULT ((0)) FOR [GUIDE_RUN_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_MANUAL_HIGH_SPD]  DEFAULT ((0)) FOR [GUIDE_MANUAL_HIGH_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_MANUAL_LOW_SPD]  DEFAULT ((0)) FOR [GUIDE_MANUAL_LOW_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_F_L_LOCK_POSITION]  DEFAULT ((0)) FOR [GUIDE_LF_LOCK_POSITION]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_R_L_LOCK_POSITION]  DEFAULT ((0)) FOR [GUIDE_LB_LOCK_POSITION]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_F_R_LOCK_POSITION]  DEFAULT ((0)) FOR [GUIDE_RF_LOCK_POSITION]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_R_R_LOCK_POSITION]  DEFAULT ((0)) FOR [GUIDE_RB_LOCK_POSITION]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_CHG_STABLE_TIME]  DEFAULT ((0)) FOR [GUIDE_CHG_STABLE_TIME]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_RESOLUTION]  DEFAULT ((0)) FOR [TRAVEL_RESOLUTION]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_START_STOP_SPEED]  DEFAULT ((0)) FOR [TRAVEL_START_STOP_SPEED]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_MAX_SPD]  DEFAULT ((0)) FOR [TRAVEL_MAX_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_ACCEL_DECCEL_TIME]  DEFAULT ((0)) FOR [TRAVEL_ACCEL_DECCEL_TIME]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_S_CURVE_RATE]  DEFAULT ((0)) FOR [TRAVEL_S_CURVE_RATE]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_HOME_DIR]  DEFAULT ((0)) FOR [TRAVEL_HOME_DIR]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_HOME_SPD]  DEFAULT ((0)) FOR [TRAVEL_HOME_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_KEEP_DIS_SPD]  DEFAULT ((0)) FOR [TRAVEL_KEEP_DIS_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_MANUAL_HIGH_SPD]  DEFAULT ((0)) FOR [TRAVEL_MANUAL_HIGH_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_MANUAL_LOW_SPD]  DEFAULT ((0)) FOR [TRAVEL_MANUAL_LOW_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_TEACHING_SPD]  DEFAULT ((0)) FOR [TRAVEL_TEACHING_SPD]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_TRAVEL_DIR]  DEFAULT ((0)) FOR [TRAVEL_TRAVEL_DIR]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_ENCODER_POLARITY]  DEFAULT ((0)) FOR [TRAVEL_ENCODER_POLARITY]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_F_DIR_LIMIT]  DEFAULT ((0)) FOR [TRAVEL_F_DIR_LIMIT]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_R_DIR_LIMIT]  DEFAULT ((0)) FOR [TRAVEL_R_DIR_LIMIT]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_OBS_DETECT_LONG]  DEFAULT ((0)) FOR [TRAVEL_OBS_DETECT_LONG]
GO
ALTER TABLE [dbo].[AVEHICLE_CONTROL_100] ADD  CONSTRAINT [DF_AVEHICLE_CONTROL_100_TRAVEL_OBS_DETECT_SHORT]  DEFAULT ((0)) FOR [TRAVEL_OBS_DETECT_SHORT]
GO
ALTER TABLE [dbo].[AVIDINFO] ADD  CONSTRAINT [DF_AVIDINFO_REPLACE_1]  DEFAULT ((0)) FOR [REPLACE]
GO
ALTER TABLE [dbo].[CassetteData] ADD  CONSTRAINT [DF_CassetteData_Stage]  DEFAULT ((1)) FOR [Stage]
GO
ALTER TABLE [dbo].[CassetteData] ADD  CONSTRAINT [DF_CassetteData_CSTState]  DEFAULT ((0)) FOR [CSTState]
GO
ALTER TABLE [dbo].[CassetteData] ADD  CONSTRAINT [DF_CassetteData_EmptyCST]  DEFAULT ((0)) FOR [EmptyCST]
GO
ALTER TABLE [dbo].[CassetteData] ADD  CONSTRAINT [DF_CassetteData_CSTType]  DEFAULT ((0)) FOR [CSTType]
GO
ALTER TABLE [dbo].[HASHEET] ADD  DEFAULT ((0)) FOR [PROC_FLAG]
GO
ALTER TABLE [dbo].[HASHEET] ADD  DEFAULT ((0)) FOR [PROC_INFO]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_State]  DEFAULT ((1)) FOR [State]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_Stage]  DEFAULT ((1)) FOR [Stage]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_AGVState]  DEFAULT ((2)) FOR [AGVState]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_AGVPortTypeDef]  DEFAULT ((0)) FOR [PortTypeDef]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_PortLocationType]  DEFAULT ((2)) FOR [PortLocationType]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_SourceWeighted]  DEFAULT ((0)) FOR [SourceWeighted]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_DestWeighted]  DEFAULT ((0)) FOR [DestWeighted]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_Direction]  DEFAULT ((0)) FOR [Direction]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_TimeOutForAutoUD]  DEFAULT ((0)) FOR [TimeOutForAutoUD]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_Vehicles]  DEFAULT ((1)) FOR [Vehicles]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_Floor]  DEFAULT ((0)) FOR [Floor]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_IgnoreModeChange]  DEFAULT ('N') FOR [IgnoreModeChange]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_ReportMCSFlag]  DEFAULT ('Y') FOR [ReportMCSFlag]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_ReportStage]  DEFAULT ((0)) FOR [ReportStage]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_NetHStnNo]  DEFAULT ((0)) FOR [NetHStnNo]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_AreaSensorStnNo]  DEFAULT ((0)) FOR [AreaSensorStnNo]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_Presenton_InsCST]  DEFAULT ('N') FOR [Presenton_InsCST]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_Presentoff_DelCST]  DEFAULT ('N') FOR [Presentoff_DelCST]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_AlarmType]  DEFAULT ((3)) FOR [AlarmType]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_PortGroup]  DEFAULT ((1)) FOR [PortGroup]
GO
ALTER TABLE [dbo].[PortDef] ADD  CONSTRAINT [DF_PortDef_PRIORITY]  DEFAULT ((0)) FOR [PRIORITY]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_Stage]  DEFAULT ((1)) FOR [Stage]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_LocateCraneNo]  DEFAULT ((11)) FOR [LocateCraneNo]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_ShelfType]  DEFAULT ((1)) FOR [ShelfType]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_ShelfState]  DEFAULT ('N') FOR [ShelfState]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_Enable]  DEFAULT ('0') FOR [Enable]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_OldEnableSts]  DEFAULT ('Y') FOR [OldEnableSts]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_EmptyBlockFlag]  DEFAULT ('N') FOR [EmptyBlockFlag]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_HoldState]  DEFAULT ((0)) FOR [HoldState]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_BCRReadFlag]  DEFAULT ('Y') FOR [BCRReadFlag]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_TransferTimes]  DEFAULT ((0)) FOR [TransferTimes]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_ChargeLoc]  DEFAULT ('N') FOR [ChargeLoc]
GO
ALTER TABLE [dbo].[ShelfDef] ADD  CONSTRAINT [DF_ShelfDef_SelectPriority]  DEFAULT ((0)) FOR [SelectPriority]
GO
ALTER TABLE [dbo].[ZoneDef] ADD  CONSTRAINT [DF_ZoneDef_HighWaterMark]  DEFAULT ((0)) FOR [HighWaterMark]
GO
ALTER TABLE [dbo].[ZoneDef] ADD  CONSTRAINT [DF_ZoneDef_LowWaterMark]  DEFAULT ((0)) FOR [LowWaterMark]
GO
ALTER TABLE [dbo].[ZoneDef] ADD  CONSTRAINT [DF_ZoneDef_ZoneType]  DEFAULT ((1)) FOR [ZoneType]
GO
ALTER TABLE [dbo].[ZoneDef] ADD  CONSTRAINT [DF_ZoneDef_InventoryCheck]  DEFAULT ('Y') FOR [InventoryCheck]
GO
ALTER TABLE [dbo].[ZoneDef] ADD  CONSTRAINT [DF_ZoneDef_Color]  DEFAULT ('#000000') FOR [Color]
GO
ALTER TABLE [dbo].[ZoneDef] ADD  CONSTRAINT [DF_ZoneDef_SourceWeighted]  DEFAULT ((0)) FOR [SourceWeighted]
GO
ALTER TABLE [dbo].[ZoneDef] ADD  CONSTRAINT [DF_ZoneDef_DestWeighted]  DEFAULT ((0)) FOR [DestWeighted]
GO
USE [master]
GO
ALTER DATABASE [OHBC_ASE_K21_LINE1] SET  READ_WRITE 
GO
