//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.bc.winform.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.mirle.ibg3k0.bc.winform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Accel / Deccel Time 的當地語系化字串。
        /// </summary>
        public static string Accel_Deccel_Time {
            get {
                return ResourceManager.GetString("Accel_Deccel_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Cassette_ {
            get {
                object obj = ResourceManager.GetObject("Action__Cassette_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Correcting_action_ {
            get {
                object obj = ResourceManager.GetObject("Action__Correcting_action_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Loading_ {
            get {
                object obj = ResourceManager.GetObject("Action__Loading_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Maintenance_ {
            get {
                object obj = ResourceManager.GetObject("Action__Maintenance_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Moving_ {
            get {
                object obj = ResourceManager.GetObject("Action__Moving_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Parked_ {
            get {
                object obj = ResourceManager.GetObject("Action__Parked_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Parking_ {
            get {
                object obj = ResourceManager.GetObject("Action__Parking_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Receive_command_ {
            get {
                object obj = ResourceManager.GetObject("Action__Receive_command_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Action__Unloading_ {
            get {
                object obj = ResourceManager.GetObject("Action__Unloading_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Address Data 的當地語系化字串。
        /// </summary>
        public static string Address_Data {
            get {
                return ResourceManager.GetString("Address_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address ID 的當地語系化字串。
        /// </summary>
        public static string Address_ID {
            get {
                return ResourceManager.GetString("Address_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Alarm__Alert_ {
            get {
                object obj = ResourceManager.GetObject("Alarm__Alert_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Alarm__Error_ {
            get {
                object obj = ResourceManager.GetObject("Alarm__Error_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Alarm__Warning_ {
            get {
                object obj = ResourceManager.GetObject("Alarm__Warning_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap alert_red_org {
            get {
                object obj = ResourceManager.GetObject("alert_red_org", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Area Sensor-1 的當地語系化字串。
        /// </summary>
        public static string Area_Sensor_1 {
            get {
                return ResourceManager.GetString("Area_Sensor_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Area Sensor-2 的當地語系化字串。
        /// </summary>
        public static string Area_Sensor_2 {
            get {
                return ResourceManager.GetString("Area_Sensor_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap arrow_two_head {
            get {
                object obj = ResourceManager.GetObject("arrow_two_head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap arrow1 {
            get {
                object obj = ResourceManager.GetObject("arrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap arrowDown {
            get {
                object obj = ResourceManager.GetObject("arrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap arrowUP {
            get {
                object obj = ResourceManager.GetObject("arrowUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap aw {
            get {
                object obj = ResourceManager.GetObject("aw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap aw1 {
            get {
                object obj = ResourceManager.GetObject("aw1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap aw11 {
            get {
                object obj = ResourceManager.GetObject("aw11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap aw2 {
            get {
                object obj = ResourceManager.GetObject("aw2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap b1 {
            get {
                object obj = ResourceManager.GetObject("b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Ball_Bule {
            get {
                object obj = ResourceManager.GetObject("Ball_Bule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Ball_Green {
            get {
                object obj = ResourceManager.GetObject("Ball_Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Ball_Red {
            get {
                object obj = ResourceManager.GetObject("Ball_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Ball_Yellow {
            get {
                object obj = ResourceManager.GetObject("Ball_Yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap brlight {
            get {
                object obj = ResourceManager.GetObject("brlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap buf_glight {
            get {
                object obj = ResourceManager.GetObject("buf_glight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap bufferglight {
            get {
                object obj = ResourceManager.GetObject("bufferglight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Change Stability Time 的當地語系化字串。
        /// </summary>
        public static string Change_Stability_Time {
            get {
                return ResourceManager.GetString("Change_Stability_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Circle_Green {
            get {
                object obj = ResourceManager.GetObject("Circle_Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Circle_Red {
            get {
                object obj = ResourceManager.GetObject("Circle_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap clear1 {
            get {
                object obj = ResourceManager.GetObject("clear1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap close_24 {
            get {
                object obj = ResourceManager.GetObject("close_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Collision Avoidance : Forward Straight 的當地語系化字串。
        /// </summary>
        public static string Collision_Avoidance_Forward_Straight {
            get {
                return ResourceManager.GetString("Collision_Avoidance_Forward_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collision Avoidance : Left Straight 的當地語系化字串。
        /// </summary>
        public static string Collision_Avoidance_Left_Straight {
            get {
                return ResourceManager.GetString("Collision_Avoidance_Left_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collision Avoidance : Right Straight 的當地語系化字串。
        /// </summary>
        public static string Collision_Avoidance_Right_Straight {
            get {
                return ResourceManager.GetString("Collision_Avoidance_Right_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Control Data 的當地語系化字串。
        /// </summary>
        public static string Control_Data {
            get {
                return ResourceManager.GetString("Control_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Control Setting 的當地語系化字串。
        /// </summary>
        public static string Control_Setting {
            get {
                return ResourceManager.GetString("Control_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap conver_E {
            get {
                object obj = ResourceManager.GetObject("conver_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap conver_F {
            get {
                object obj = ResourceManager.GetObject("conver_F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Crane1 {
            get {
                object obj = ResourceManager.GetObject("Crane1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Dircetion of Home 的當地語系化字串。
        /// </summary>
        public static string Dircetion_of_Home {
            get {
                return ResourceManager.GetString("Dircetion_of_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Direction of Guide-1 的當地語系化字串。
        /// </summary>
        public static string Direction_of_Guide_1 {
            get {
                return ResourceManager.GetString("Direction_of_Guide_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Direction of Guide-2 的當地語系化字串。
        /// </summary>
        public static string Direction_of_Guide_2 {
            get {
                return ResourceManager.GetString("Direction_of_Guide_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Direction of Read 的當地語系化字串。
        /// </summary>
        public static string Direction_of_Read {
            get {
                return ResourceManager.GetString("Direction_of_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Done {
            get {
                object obj = ResourceManager.GetObject("Done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap down1 {
            get {
                object obj = ResourceManager.GetObject("down1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Down2 {
            get {
                object obj = ResourceManager.GetObject("Down2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Drive Dir. 的當地語系化字串。
        /// </summary>
        public static string Drive_Dir {
            get {
                return ResourceManager.GetString("Drive_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap edit_clear {
            get {
                object obj = ResourceManager.GetObject("edit_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap edit_undo {
            get {
                object obj = ResourceManager.GetObject("edit_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap edit1 {
            get {
                object obj = ResourceManager.GetObject("edit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap edit1_PPID {
            get {
                object obj = ResourceManager.GetObject("edit1_PPID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap edit1_Recipe {
            get {
                object obj = ResourceManager.GetObject("edit1_Recipe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Change Guide Area 的當地語系化字串。
        /// </summary>
        public static string Enable_Change_Guide_Area {
            get {
                return ResourceManager.GetString("Enable_Change_Guide_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap enginner {
            get {
                object obj = ResourceManager.GetObject("enginner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap EXCLEM {
            get {
                object obj = ResourceManager.GetObject("EXCLEM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap exit01 {
            get {
                object obj = ResourceManager.GetObject("exit01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap export1 {
            get {
                object obj = ResourceManager.GetObject("export1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap folder_clock {
            get {
                object obj = ResourceManager.GetObject("folder_clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap FOLDER01 {
            get {
                object obj = ResourceManager.GetObject("FOLDER01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap FORM {
            get {
                object obj = ResourceManager.GetObject("FORM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap forum {
            get {
                object obj = ResourceManager.GetObject("forum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Front-Left Lock Position 的當地語系化字串。
        /// </summary>
        public static string Front_Left_Lock_Position {
            get {
                return ResourceManager.GetString("Front_Left_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Front Limit 的當地語系化字串。
        /// </summary>
        public static string Front_Limit {
            get {
                return ResourceManager.GetString("Front_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Front-Right Lock Position 的當地語系化字串。
        /// </summary>
        public static string Front_Right_Lock_Position {
            get {
                return ResourceManager.GetString("Front_Right_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap futaba {
            get {
                object obj = ResourceManager.GetObject("futaba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Futaba1 {
            get {
                object obj = ResourceManager.GetObject("Futaba1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap GEARWEEL {
            get {
                object obj = ResourceManager.GetObject("GEARWEEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap gnome_go_top {
            get {
                object obj = ResourceManager.GetObject("gnome_go_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap GRAPH01 {
            get {
                object obj = ResourceManager.GetObject("GRAPH01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap GRAPH04 {
            get {
                object obj = ResourceManager.GetObject("GRAPH04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap gray {
            get {
                object obj = ResourceManager.GetObject("gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap gray1 {
            get {
                object obj = ResourceManager.GetObject("gray1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap group {
            get {
                object obj = ResourceManager.GetObject("group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Guide Data 的當地語系化字串。
        /// </summary>
        public static string Guide_Data {
            get {
                return ResourceManager.GetString("Guide_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Guide Dir. 的當地語系化字串。
        /// </summary>
        public static string Guide_Dir {
            get {
                return ResourceManager.GetString("Guide_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Handle {
            get {
                object obj = ResourceManager.GetObject("Handle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Home Speed 的當地語系化字串。
        /// </summary>
        public static string Home_Speed {
            get {
                return ResourceManager.GetString("Home_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap home_w3 {
            get {
                object obj = ResourceManager.GetObject("home_w3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap home4 {
            get {
                object obj = ResourceManager.GetObject("home4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap home5 {
            get {
                object obj = ResourceManager.GetObject("home5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Inposition Area 的當地語系化字串。
        /// </summary>
        public static string Inposition_Area {
            get {
                return ResourceManager.GetString("Inposition_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inposition Stability Time 的當地語系化字串。
        /// </summary>
        public static string Inposition_Stability_Time {
            get {
                return ResourceManager.GetString("Inposition_Stability_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Distance - Far 的當地語系化字串。
        /// </summary>
        public static string Keep_Distance_Far {
            get {
                return ResourceManager.GetString("Keep_Distance_Far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Distance - Near 的當地語系化字串。
        /// </summary>
        public static string Keep_Distance_Near {
            get {
                return ResourceManager.GetString("Keep_Distance_Near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Distance Speed 的當地語系化字串。
        /// </summary>
        public static string Keep_Distance_Speed {
            get {
                return ResourceManager.GetString("Keep_Distance_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Laser Sensor : Forward Straight 的當地語系化字串。
        /// </summary>
        public static string Laser_Sensor_Forward_Straight {
            get {
                return ResourceManager.GetString("Laser_Sensor_Forward_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap leve2 {
            get {
                object obj = ResourceManager.GetObject("leve2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap leve3 {
            get {
                object obj = ResourceManager.GetObject("leve3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap level {
            get {
                object obj = ResourceManager.GetObject("level", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap level1 {
            get {
                object obj = ResourceManager.GetObject("level1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap level5 {
            get {
                object obj = ResourceManager.GetObject("level5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap level51 {
            get {
                object obj = ResourceManager.GetObject("level51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap level6 {
            get {
                object obj = ResourceManager.GetObject("level6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap level61 {
            get {
                object obj = ResourceManager.GetObject("level61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Lifter_E {
            get {
                object obj = ResourceManager.GetObject("Lifter_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Lifter_F {
            get {
                object obj = ResourceManager.GetObject("Lifter_F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap List {
            get {
                object obj = ResourceManager.GetObject("List", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap list_edit {
            get {
                object obj = ResourceManager.GetObject("list_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap lock_yellow {
            get {
                object obj = ResourceManager.GetObject("lock_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap lock1 {
            get {
                object obj = ResourceManager.GetObject("lock1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Maunual High Speed 的當地語系化字串。
        /// </summary>
        public static string Maunual_High_Speed {
            get {
                return ResourceManager.GetString("Maunual_High_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maunual Low Speed 的當地語系化字串。
        /// </summary>
        public static string Maunual_Low_Speed {
            get {
                return ResourceManager.GetString("Maunual_Low_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max Speed 的當地語系化字串。
        /// </summary>
        public static string Max_Speed {
            get {
                return ResourceManager.GetString("Max_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Mini_Tools {
            get {
                object obj = ResourceManager.GetObject("Mini-Tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap MiningModel {
            get {
                object obj = ResourceManager.GetObject("MiningModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Mirle {
            get {
                object obj = ResourceManager.GetObject("Mirle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Mirle_Loading_9 {
            get {
                object obj = ResourceManager.GetObject("Mirle_Loading_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Mirle1 {
            get {
                object obj = ResourceManager.GetObject("Mirle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Mirle2 {
            get {
                object obj = ResourceManager.GetObject("Mirle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Mirle3 {
            get {
                object obj = ResourceManager.GetObject("Mirle3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap MISC14 {
            get {
                object obj = ResourceManager.GetObject("MISC14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Monitor {
            get {
                object obj = ResourceManager.GetObject("Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap noorder {
            get {
                object obj = ResourceManager.GetObject("noorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap noorder1 {
            get {
                object obj = ResourceManager.GetObject("noorder1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap note2 {
            get {
                object obj = ResourceManager.GetObject("note2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap oglight {
            get {
                object obj = ResourceManager.GetObject("oglight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Operation {
            get {
                object obj = ResourceManager.GetObject("Operation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ovenrlight {
            get {
                object obj = ResourceManager.GetObject("ovenrlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap passwordChange {
            get {
                object obj = ResourceManager.GetObject("passwordChange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap PasswordOff {
            get {
                object obj = ResourceManager.GetObject("PasswordOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Pause__Block_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Block_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Pause__Earthquake_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Earthquake_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Pause__HID_ {
            get {
                object obj = ResourceManager.GetObject("Pause__HID_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Pause__Obstructed_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Obstructed_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Pause__Pause_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Pause_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Pause__Safety_ {
            get {
                object obj = ResourceManager.GetObject("Pause__Safety_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap pin_blue {
            get {
                object obj = ResourceManager.GetObject("pin_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap PlayBlue {
            get {
                object obj = ResourceManager.GetObject("PlayBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap player_stop {
            get {
                object obj = ResourceManager.GetObject("player_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Pole of Encoder 的當地語系化字串。
        /// </summary>
        public static string Pole_of_Encoder {
            get {
                return ResourceManager.GetString("Pole_of_Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Position 的當地語系化字串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Presence Address Report 的當地語系化字串。
        /// </summary>
        public static string Presence_Address_Report {
            get {
                return ResourceManager.GetString("Presence_Address_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Presence Blocking Request 的當地語系化字串。
        /// </summary>
        public static string Presence_Blocking_Request {
            get {
                return ResourceManager.GetString("Presence_Blocking_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Presence Diverge 的當地語系化字串。
        /// </summary>
        public static string Presence_Diverge {
            get {
                return ResourceManager.GetString("Presence_Diverge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Presence HID Control 的當地語系化字串。
        /// </summary>
        public static string Presence_HID_Control {
            get {
                return ResourceManager.GetString("Presence_HID_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Query {
            get {
                object obj = ResourceManager.GetObject("Query", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap quit {
            get {
                object obj = ResourceManager.GetObject("quit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Rear-Left Lock Position 的當地語系化字串。
        /// </summary>
        public static string Rear_Left_Lock_Position {
            get {
                return ResourceManager.GetString("Rear_Left_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rear Limit 的當地語系化字串。
        /// </summary>
        public static string Rear_Limit {
            get {
                return ResourceManager.GetString("Rear_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rear-Right Lock Position 的當地語系化字串。
        /// </summary>
        public static string Rear_Right_Lock_Position {
            get {
                return ResourceManager.GetString("Rear_Right_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap redline {
            get {
                object obj = ResourceManager.GetObject("redline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap refresh1 {
            get {
                object obj = ResourceManager.GetObject("refresh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Resolution 的當地語系化字串。
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap robot {
            get {
                object obj = ResourceManager.GetObject("robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Running Speed 的當地語系化字串。
        /// </summary>
        public static string Running_Speed {
            get {
                return ResourceManager.GetString("Running_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 S Curve Rate 的當地語系化字串。
        /// </summary>
        public static string S_Curve_Rate {
            get {
                return ResourceManager.GetString("S_Curve_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap saveall_24 {
            get {
                object obj = ResourceManager.GetObject("saveall_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale Data 的當地語系化字串。
        /// </summary>
        public static string Scale_Data {
            get {
                return ResourceManager.GetString("Scale_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale Offset 的當地語系化字串。
        /// </summary>
        public static string Scale_Offset {
            get {
                return ResourceManager.GetString("Scale_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale Reset Distance 的當地語系化字串。
        /// </summary>
        public static string Scale_Reset_Distance {
            get {
                return ResourceManager.GetString("Scale_Reset_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap screen_on {
            get {
                object obj = ResourceManager.GetObject("screen_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap se {
            get {
                object obj = ResourceManager.GetObject("se", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap search02 {
            get {
                object obj = ResourceManager.GetObject("search02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Section ID 的當地語系化字串。
        /// </summary>
        public static string SEC_ID {
            get {
                return ResourceManager.GetString("SEC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section Data 的當地語系化字串。
        /// </summary>
        public static string Section_Data {
            get {
                return ResourceManager.GetString("Section_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section Distance 的當地語系化字串。
        /// </summary>
        public static string Section_Distance {
            get {
                return ResourceManager.GetString("Section_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section ID 的當地語系化字串。
        /// </summary>
        public static string Section_ID {
            get {
                return ResourceManager.GetString("Section_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Section Speed 的當地語系化字串。
        /// </summary>
        public static string Section_Speed {
            get {
                return ResourceManager.GetString("Section_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Segment No. 的當地語系化字串。
        /// </summary>
        public static string Segment_No {
            get {
                return ResourceManager.GetString("Segment_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Segment Number-1 的當地語系化字串。
        /// </summary>
        public static string Segment_Number_1 {
            get {
                return ResourceManager.GetString("Segment_Number_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Segment Number-2 的當地語系化字串。
        /// </summary>
        public static string Segment_Number_2 {
            get {
                return ResourceManager.GetString("Segment_Number_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sensor Setting 的當地語系化字串。
        /// </summary>
        public static string Sensor_Setting {
            get {
                return ResourceManager.GetString("Sensor_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap services {
            get {
                object obj = ResourceManager.GetObject("services", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap show {
            get {
                object obj = ResourceManager.GetObject("show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap sign_out1 {
            get {
                object obj = ResourceManager.GetObject("sign_out1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap single_0 {
            get {
                object obj = ResourceManager.GetObject("single_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap single_1 {
            get {
                object obj = ResourceManager.GetObject("single_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap single_2 {
            get {
                object obj = ResourceManager.GetObject("single_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap single_3 {
            get {
                object obj = ResourceManager.GetObject("single_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap single_4 {
            get {
                object obj = ResourceManager.GetObject("single_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap single_5 {
            get {
                object obj = ResourceManager.GetObject("single_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Speed__Fast_ {
            get {
                object obj = ResourceManager.GetObject("Speed__Fast_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Speed__Medium_ {
            get {
                object obj = ResourceManager.GetObject("Speed__Medium_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Speed__Slow_ {
            get {
                object obj = ResourceManager.GetObject("Speed__Slow_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Start / Stop Speed 的當地語系化字串。
        /// </summary>
        public static string Start_Stop_Speed {
            get {
                return ResourceManager.GetString("Start_Stop_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Teaching Speed 的當地語系化字串。
        /// </summary>
        public static string Teaching_Speed {
            get {
                return ResourceManager.GetString("Teaching_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap terminal {
            get {
                object obj = ResourceManager.GetObject("terminal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap th_list {
            get {
                object obj = ResourceManager.GetObject("th_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap th_small {
            get {
                object obj = ResourceManager.GetObject("th_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of Blocking Response 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_Blocking_Response {
            get {
                return ResourceManager.GetString("Timeout_of_Blocking_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T1 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_T1 {
            get {
                return ResourceManager.GetString("Timeout_of_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T2 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_T2 {
            get {
                return ResourceManager.GetString("Timeout_of_T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T3 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_T3 {
            get {
                return ResourceManager.GetString("Timeout_of_T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T4 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_T4 {
            get {
                return ResourceManager.GetString("Timeout_of_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T5 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_T5 {
            get {
                return ResourceManager.GetString("Timeout_of_T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T6 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_T6 {
            get {
                return ResourceManager.GetString("Timeout_of_T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T7 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_T7 {
            get {
                return ResourceManager.GetString("Timeout_of_T7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timeout of T8 的當地語系化字串。
        /// </summary>
        public static string Timeout_of_T8 {
            get {
                return ResourceManager.GetString("Timeout_of_T8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap tools {
            get {
                object obj = ResourceManager.GetObject("tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Pulse Of One Scale 的當地語系化字串。
        /// </summary>
        public static string Total_Pulse_Of_One_Scale {
            get {
                return ResourceManager.GetString("Total_Pulse_Of_One_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap transfer {
            get {
                object obj = ResourceManager.GetObject("transfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap transfer_right_left {
            get {
                object obj = ResourceManager.GetObject("transfer_right_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Travel Base Data 的當地語系化字串。
        /// </summary>
        public static string Travel_Base_Data {
            get {
                return ResourceManager.GetString("Travel_Base_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Travel Direction 的當地語系化字串。
        /// </summary>
        public static string Travel_Direction {
            get {
                return ResourceManager.GetString("Travel_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap TRU_L {
            get {
                object obj = ResourceManager.GetObject("TRU_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap TRU_R {
            get {
                object obj = ResourceManager.GetObject("TRU_R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap undo16 {
            get {
                object obj = ResourceManager.GetObject("undo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap undo24 {
            get {
                object obj = ResourceManager.GetObject("undo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap undo24_1 {
            get {
                object obj = ResourceManager.GetObject("undo24_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Time :  的當地語系化字串。
        /// </summary>
        public static string Update_Time {
            get {
                return ResourceManager.GetString("Update_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update User :  的當地語系化字串。
        /// </summary>
        public static string Update_User {
            get {
                return ResourceManager.GetString("Update_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap User1 {
            get {
                object obj = ResourceManager.GetObject("User1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap user11 {
            get {
                object obj = ResourceManager.GetObject("user11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap User2 {
            get {
                object obj = ResourceManager.GetObject("User2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Vehicle__Auto_Local_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Auto_Local_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Vehicle__Auto_Remote_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Auto_Remote_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Vehicle__Manual_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Manual_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Vehicle__Power_on_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Power_on_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Vehicle__Unconnected_ {
            get {
                object obj = ResourceManager.GetObject("Vehicle__Unconnected_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Vehicle_display_V2_3 {
            get {
                object obj = ResourceManager.GetObject("Vehicle_display_V2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Vehicle ID 的當地語系化字串。
        /// </summary>
        public static string Vehicle_ID {
            get {
                return ResourceManager.GetString("Vehicle_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap W95MBX03 {
            get {
                object obj = ResourceManager.GetObject("W95MBX03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap wlm {
            get {
                object obj = ResourceManager.GetObject("wlm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap 小型_彩色Logo {
            get {
                object obj = ResourceManager.GetObject("小型_彩色Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap 小型_彩色Logo_去背 {
            get {
                object obj = ResourceManager.GetObject("小型_彩色Logo_去背", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap 小型_彩色Logo1 {
            get {
                object obj = ResourceManager.GetObject("小型_彩色Logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap 漸層 {
            get {
                object obj = ResourceManager.GetObject("漸層", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap 短式_彩色Logo_去背 {
            get {
                object obj = ResourceManager.GetObject("短式_彩色Logo_去背", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap 短式_彩色Logo_去背1 {
            get {
                object obj = ResourceManager.GetObject("短式_彩色Logo_去背1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
