//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AADDRESS
    {
        public string ADR_ID { get; set; }
        public E_ADR_TYPE ADRTYPE { get; set; }
        public string SEC_ID { get; set; }
        public Nullable<int> DISTANCE { get; set; }
        public string CS_NUMBER { get; set; }
        public string T_PULSE { get; set; }
        public string P_LOCATION { get; set; }
        public int IS_DISPLAY { get; set; }
        public int ZOOM_LV { get; set; }
        public string BAR_CODE { get; set; }
        public int OFFSET_X { get; set; }
        public int OFFSET_Y { get; set; }
        public int OFFSET_Z { get; set; }
        public int OFFSET_T { get; set; }
        public string PIO_ID { get; set; }
        public int PIO_CHN { get; set; }
        public string PORT1_ID { get; set; }
        public E_VH_TYPE P1_LD_VH_TYPE { get; set; }
        public E_VH_TYPE P1_ULD_VH_TYPE { get; set; }
        public string PORT2_ID { get; set; }
        public E_VH_TYPE P2_LD_VH_TYPE { get; set; }
        public E_VH_TYPE P2_ULD_VH_TYPE { get; set; }
    }
}
