//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACASSETTE
    {
        public string CST_ID { get; set; }
        public int CST_STAT { get; set; }
        public int SHT_CNT { get; set; }
        public string PORT_ID { get; set; }
        public string CST_CODE { get; set; }
        public string LOT_ID { get; set; }
        public string SLOT_MAP { get; set; }
        public string SLOT_SEL { get; set; }
        public string END_STAT { get; set; }
        public string CRATE_ID { get; set; }
        public Nullable<System.DateTime> CSTLOGON_TIME { get; set; }
        public Nullable<System.DateTime> CSTLOGOff_TIME { get; set; }
        public string ISLOTSTART { get; set; }
        public Nullable<System.DateTime> CSTPROCSTART_TIME { get; set; }
        public Nullable<System.DateTime> CSTPROCEND_TIME { get; set; }
        public string ROUNTINMODE { get; set; }
    }
}
