//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACMD_OHTC_DETAIL
    {
        public string CMD_ID { get; set; }
        public int SEQ_NO { get; set; }
        public string ADD_ID { get; set; }
        public Nullable<System.DateTime> ADD_ENTRY_TIME { get; set; }
        public string SEC_ID { get; set; }
        public Nullable<System.DateTime> SEC_ENTRY_TIME { get; set; }
        public Nullable<System.DateTime> SEC_LEAVE_TIME { get; set; }
        public Nullable<System.DateTime> LOAD_START_TIME { get; set; }
        public Nullable<System.DateTime> LOAD_END_TIME { get; set; }
        public Nullable<System.DateTime> UNLOAD_START_TIME { get; set; }
        public Nullable<System.DateTime> UNLOAD_END_TIME { get; set; }
        public int ESTIMATED_TIME { get; set; }
        public bool IS_PASS { get; set; }
        public string SEG_NUM { get; set; }
    }
}
