//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACYCLEZONEMASTER
    {
        public string CYCLE_TYPE_ID { get; set; }
        public string CYCLE_ZONE_ID { get; set; }
        public string ENTRY_ADR_ID { get; set; }
        public int TOTAL_BORDER { get; set; }
        public E_VH_TYPE VEHICLE_TYPE { get; set; }
    }
}
