//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AECDATAMAP
    {
        public string ECID { get; set; }
        public string EQPT_REAL_ID { get; set; }
        public string ECNAME { get; set; }
        public string ECMIN { get; set; }
        public string ECMAX { get; set; }
        public string ECV { get; set; }
    }
}
