//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEQPT
    {
        public string EQPT_ID { get; set; }
        public string NODE_ID { get; set; }
        public string CIM_MODE { get; set; }
        public string OPER_MODE { get; set; }
        public string INLINE_MODE { get; set; }
        public string EQPT_STAT { get; set; }
        public string EQPT_PROC_STAT { get; set; }
        public string CR_RECIPE { get; set; }
        public Nullable<int> MAX_SHT_CNT { get; set; }
        public Nullable<int> MIN_SHT_CNT { get; set; }
        public string ALARM_STAT { get; set; }
        public string WARN_STAT { get; set; }
    }
}
