//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHIDZONEMASTER
    {
        public string ENTRY_SEC_ID { get; set; }
        public string LEAVE_ADR_ID_1 { get; set; }
        public string LEAVE_ADR_ID_2 { get; set; }
        public int MAX_LOAD_COUNT { get; set; }
    }
}
