//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHIDZONEQUEUE
    {
        public string ENTRY_SEC_ID { get; set; }
        public string VEHICLE_ID { get; set; }
        public System.DateTime REQ_TIME { get; set; }
        public Nullable<System.DateTime> BLOCK_TIME { get; set; }
        public Nullable<System.DateTime> THROU_TIME { get; set; }
        public Nullable<System.DateTime> RELEASE_TIME { get; set; }
        public E_HIDQueueStatus STATUS { get; set; }
        public bool IS_PASUE { get; set; }
    }
}
