//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALARM
    {
        public string EQPT_ID { get; set; }
        public int UNIT_NUM { get; set; }
        public string RPT_DATE_TIME { get; set; }
        public string ALAM_CODE { get; set; }
        public E_ALARM_LVL ALAM_LVL { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.ErrorStatus ALAM_STAT { get; set; }
        public string ALAM_DESC { get; set; }
        /// <summary>
        /// 用來作為是否已經上報給MCS的Flag，已上報為Y，未上報的為N
        /// </summary>
        public string ERROR_ID { get; set; }
        public string UnitID { get; set; }
        public string UnitState { get; set; }
        public string RecoveryOption { get; set; }
        public string CMD_ID { get; set; }
        public string END_TIME { get; set; }
    }
}
