//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALOT
    {
        public string LOT_ID { get; set; }
        public string SHT_TYP { get; set; }
        public string CST_OPER_MODE { get; set; }
        public string DUMMY_TYPE { get; set; }
        public string LOT_JUDGE { get; set; }
        public string WORK_ORDER { get; set; }
        public string PROC_STAT { get; set; }
        public string LOT_START_PROC_TIME { get; set; }
        public string LOT_END_PROC_TIME { get; set; }
        public Nullable<int> PROC_SHT_CNT { get; set; }
    }
}
