//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMCSREPORTQUEUE
    {
        public System.Guid ID { get; set; }
        public byte[] SERIALIZED_SXFY { get; set; }
        public System.DateTime INTER_TIME { get; set; }
        public Nullable<System.DateTime> REPORT_TIME { get; set; }
        public string STREAMFUNCTION_NAME { get; set; }
        public string STREAMFUNCTION_CEID { get; set; }
        public string MCS_CMD_ID { get; set; }
        public string VEHICLE_ID { get; set; }
        public string PORT_ID { get; set; }
    }
}
