//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class APORT
    {
        public string PORT_ID { get; set; }
        public int UNIT_NUM { get; set; }
        public int PORT_NUM { get; set; }
        public string EQPT_ID { get; set; }
        public string PORT_TYPE { get; set; }
        public string PORT_USE_TYPE { get; set; }
        public string PORT_REAL_TYPE { get; set; }
        public int CAPACITY { get; set; }
        public string PORT_STAT { get; set; }
        public string PORT_ENABLE { get; set; }
        public string TRS_MODE { get; set; }
    }
}
