//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class APORTSTATION
    {
        public string PORT_ID { get; set; }
        public int ADRTYPE { get; set; }
        public string ADR_ID { get; set; }
        public E_VH_TYPE LD_VH_TYPE { get; set; }
        public E_VH_TYPE ULD_VH_TYPE { get; set; }
        public int PRIORITY { get; set; }
        public int PORT_TYPE { get; set; }
        public E_PORT_STATUS PORT_STATUS { get; set; }
        public int PORT_DIR { get; set; }
        public int PORT_SERVICE_STATUS { get; set; }
    }
}
