//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASECTION
    {
        public string SEC_ID { get; set; }
        public Nullable<int> SEC_ORDER_NUM { get; set; }
        public int SEG_ORDER_NUM { get; set; }
        public E_DIRC_DRIV DIRC_DRIV { get; set; }
        public E_DIRC_GUID DIRC_GUID { get; set; }
        public Nullable<com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.E_AreaSensorDir> AREA_SECSOR { get; set; }
        public string SEG_NUM { get; set; }
        public string FROM_ADR_ID { get; set; }
        public string TO_ADR_ID { get; set; }
        public double SEC_DIS { get; set; }
        public Nullable<double> SEC_SPD { get; set; }
        public int DIS_FROM_ORIGIN { get; set; }
        public E_DIRC_GUID CDOG_1 { get; set; }
        public string CHG_SEG_NUM_1 { get; set; }
        public E_DIRC_GUID CDOG_2 { get; set; }
        public string CHG_SEG_NUM_2 { get; set; }
        public int PRE_BLO_REQ { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.SectionType SEC_TYPE { get; set; }
        public E_RAIL_DIR SEC_DIR { get; set; }
        public int PADDING { get; set; }
        public int ENB_CHG_G_AREA { get; set; }
        public int PRE_DIV { get; set; }
        public int PRE_ADD_REPR { get; set; }
        public int OBS_SENSOR { get; set; }
        public Nullable<System.DateTime> LAST_TECH_TIME { get; set; }
        public string SUB_VER { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string ADD_USER { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string UPD_USER { get; set; }
        public int START_BC1 { get; set; }
        public int END_BC1 { get; set; }
        public int START_BC2 { get; set; }
        public int END_BC2 { get; set; }
        public int START_BC3 { get; set; }
        public int END_BC3 { get; set; }
        public string ADR1_CHG_SEC_ID_1 { get; set; }
        public int ADR1_CHG_SEC_COST_1 { get; set; }
        public string ADR1_CHG_SEC_ID_2 { get; set; }
        public int ADR1_CHG_SEC_COST_2 { get; set; }
        public string ADR1_CHG_SEC_ID_3 { get; set; }
        public int ADR1_CHG_SEC_COST_3 { get; set; }
        public string ADR2_CHG_SEC_ID_1 { get; set; }
        public int ADR2_CHG_SEC_COST_1 { get; set; }
        public string ADR2_CHG_SEC_ID_2 { get; set; }
        public int ADR2_CHG_SEC_COST_2 { get; set; }
        public string ADR2_CHG_SEC_ID_3 { get; set; }
        public int ADR2_CHG_SEC_COST_3 { get; set; }
        public int SEC_COST_From2To { get; set; }
        public int SEC_COST_To2From { get; set; }
        public bool ISBANEND_From2To { get; set; }
        public bool ISBANEND_To2From { get; set; }
        public int STATUS { get; set; }
        public string NOTE { get; set; }
        public bool PRE_DISABLE_FLAG { get; set; }
        public Nullable<System.DateTime> PRE_DISABLE_TIME { get; set; }
        public Nullable<System.DateTime> DISABLE_TIME { get; set; }
        public bool DISABLE_FLAG_USER { get; set; }
        public bool DISABLE_FLAG_SAFETY { get; set; }
        public bool DISABLE_FLAG_CHARGE { get; set; }
        public bool DISABLE_FLAG_SYSTEM { get; set; }
    }
}
