//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASEGMENT
    {
        public string SEG_NUM { get; set; }
        public E_SEG_STATUS STATUS { get; set; }
        public int SEG_TYPE { get; set; }
        public Nullable<int> SPECIAL_MARK { get; set; }
        public string RESERVE_FIELD { get; set; }
        public string NOTE { get; set; }
        public E_RAIL_DIR DIR { get; set; }
        public bool PRE_DISABLE_FLAG { get; set; }
        public Nullable<System.DateTime> PRE_DISABLE_TIME { get; set; }
        public Nullable<System.DateTime> DISABLE_TIME { get; set; }
        public bool DISABLE_FLAG_USER { get; set; }
        public bool DISABLE_FLAG_SAFETY { get; set; }
        public bool DISABLE_FLAG_HID { get; set; }
        public bool DISABLE_FLAG_SYSTEM { get; set; }
    }
}
