//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASHEET
    {
        public string SHT_ID { get; set; }
        public string JOB_NO { get; set; }
        public string LOT_ID { get; set; }
        public string PROD_ID { get; set; }
        public string SHT_STAT { get; set; }
        public string SOURCE_CST_ID { get; set; }
        public int SOURCE_SLOT_NO { get; set; }
        public int SOURCE_PORT_NO { get; set; }
        public string TARGET_CST_ID { get; set; }
        public int TARGET_SLOT_NO { get; set; }
        public int TARGET_PORT_NO { get; set; }
        public string PROC_FLAG { get; set; }
        public string SHT_JUDGE { get; set; }
        public string SHT_GRADE { get; set; }
        public string PROC_INFO { get; set; }
        public string PPID { get; set; }
        public string CRATE_ID { get; set; }
        public string TAKE_OUT_STAT { get; set; }
        public string NODE_ID { get; set; }
        public string CST_ID { get; set; }
        public int SLOT_NO { get; set; }
        public string TAKE_OUT_TIME { get; set; }
        public string SCRAP_CODE { get; set; }
        public string REASON_CODE { get; set; }
    }
}
