//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVEHICLE_CONTROL_100
    {
        public string VEHICLE_ID { get; set; }
        public int GUIDE_START_STOP_SPEED { get; set; }
        public int GUIDE_MAX_SPD { get; set; }
        public int GUIDE_ACCEL_DECCEL_TIME { get; set; }
        public int GUIDE_S_CURVE_RATE { get; set; }
        public int GUIDE_RUN_SPD { get; set; }
        public int GUIDE_MANUAL_HIGH_SPD { get; set; }
        public int GUIDE_MANUAL_LOW_SPD { get; set; }
        public int GUIDE_LF_LOCK_POSITION { get; set; }
        public int GUIDE_LB_LOCK_POSITION { get; set; }
        public int GUIDE_RF_LOCK_POSITION { get; set; }
        public int GUIDE_RB_LOCK_POSITION { get; set; }
        public int GUIDE_CHG_STABLE_TIME { get; set; }
        public int TRAVEL_RESOLUTION { get; set; }
        public int TRAVEL_START_STOP_SPEED { get; set; }
        public int TRAVEL_MAX_SPD { get; set; }
        public int TRAVEL_ACCEL_DECCEL_TIME { get; set; }
        public int TRAVEL_S_CURVE_RATE { get; set; }
        public E_DIRC_DRIV TRAVEL_HOME_DIR { get; set; }
        public int TRAVEL_HOME_SPD { get; set; }
        public int TRAVEL_KEEP_DIS_SPD { get; set; }
        public int TRAVEL_MANUAL_HIGH_SPD { get; set; }
        public int TRAVEL_MANUAL_LOW_SPD { get; set; }
        public int TRAVEL_TEACHING_SPD { get; set; }
        public E_DIRC_DRIV TRAVEL_TRAVEL_DIR { get; set; }
        public E_ENCODER_POLE TRAVEL_ENCODER_POLARITY { get; set; }
        public int TRAVEL_F_DIR_LIMIT { get; set; }
        public int TRAVEL_R_DIR_LIMIT { get; set; }
        public int TRAVEL_OBS_DETECT_LONG { get; set; }
        public int TRAVEL_OBS_DETECT_SHORT { get; set; }
        public string SUB_VER { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string ADD_USER { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string UPD_USER { get; set; }
    }
}
