//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVEHICLE
    {
        public string VEHICLE_ID { get; set; }
        public E_VH_TYPE VEHICLE_TYPE { get; set; }
        public string CUR_ADR_ID { get; set; }
        public string CUR_SEC_ID { get; set; }
        public Nullable<System.DateTime> SEC_ENTRY_TIME { get; set; }
        public double ACC_SEC_DIST { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VHModeStatus MODE_STATUS { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VHActionStatus ACT_STATUS { get; set; }
        public string MCS_CMD { get; set; }
        public string OHTC_CMD { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle BLOCK_PAUSE { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle CMD_PAUSE { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle OBS_PAUSE { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle HID_PAUSE { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle ERROR { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle EARTHQUAKE_PAUSE { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle SAFETY_DOOR_PAUSE { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle OHXC_OBS_PAUSE { get; set; }
        public com.mirle.ibg3k0.sc.ProtocolFormat.OHTMessage.VhStopSingle OHXC_BLOCK_PAUSE { get; set; }
        public int OBS_DIST { get; set; }
        public int HAS_CST { get; set; }
        public string CST_ID { get; set; }
        public string BOX_ID { get; set; }
        public string LOT_ID { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public int VEHICLE_ACC_DIST { get; set; }
        public int MANT_ACC_DIST { get; set; }
        public Nullable<System.DateTime> MANT_DATE { get; set; }
        public int GRIP_COUNT { get; set; }
        public int GRIP_MANT_COUNT { get; set; }
        public Nullable<System.DateTime> GRIP_MANT_DATE { get; set; }
        public string NODE_ADR { get; set; }
        public bool IS_PARKING { get; set; }
        public Nullable<System.DateTime> PARK_TIME { get; set; }
        public string PARK_ADR_ID { get; set; }
        public bool IS_CYCLING { get; set; }
        public Nullable<System.DateTime> CYCLERUN_TIME { get; set; }
        public string CYCLERUN_ID { get; set; }
        public bool IS_INSTALLED { get; set; }
        public Nullable<System.DateTime> INSTALLED_TIME { get; set; }
        public Nullable<System.DateTime> REMOVED_TIME { get; set; }
        public int HAS_BOX { get; set; }
    }
}
