//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVIDINFO
    {
        public string EQ_ID { get; set; }
        public string MCS_CARRIER_ID { get; set; }
        public string CARRIER_ID { get; set; }
        public string CARRIER_LOC { get; set; }
        public Nullable<System.DateTime> CARRIER_INSTALLED_TIME { get; set; }
        public string COMMAND_ID { get; set; }
        public string SOURCEPORT { get; set; }
        public string DESTPORT { get; set; }
        public int PRIORITY { get; set; }
        public int RESULT_CODE { get; set; }
        public int VEHICLE_STATE { get; set; }
        public string COMMAND_TYPE { get; set; }
        public string ALARM_ID { get; set; }
        public string ALARM_TEXT { get; set; }
        public string UNIT_ID { get; set; }
        public string PORT_ID { get; set; }
        public int REPLACE { get; set; }
    }
}
