//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CassetteData
    {
        public string StockerID { get; set; }
        public string CSTID { get; set; }
        public string BOXID { get; set; }
        public string Carrier_LOC { get; set; }
        public decimal Stage { get; set; }
        public E_CSTState CSTState { get; set; }
        public string LotID { get; set; }
        public string EmptyCST { get; set; }
        public string CSTType { get; set; }
        public string CSTInDT { get; set; }
        public string StoreDT { get; set; }
        public string WaitOutOPDT { get; set; }
        public string WaitOutLPDT { get; set; }
        public string TrnDT { get; set; }
        public string ReadStatus { get; set; }
    }
}
