//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_DATA
    {
        public int T1 { get; set; }
        public int T2 { get; set; }
        public int T3 { get; set; }
        public int T4 { get; set; }
        public int T5 { get; set; }
        public int T6 { get; set; }
        public int T7 { get; set; }
        public int T8 { get; set; }
        public int BLOCK_REQ_TIME_OUT { get; set; }
        public string SUB_VER { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string ADD_USER { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string UPD_USER { get; set; }
    }
}
