//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    
    public enum E_CMD_TYPE : int
    {
        Move = 0,
        Move_Park = 1,
        Move_MTPort = 2,
        Load = 3,
        Unload = 4,
        LoadUnload = 5,
        Teaching = 6,
        Continue = 7,
        Round = 8,
        Home = 9,
        Override = 10,
        MTLHome = 11,
        MoveToMTL = 12,
        SystemOut = 13,
        SystemIn = 14,
        Scan = 15
    }
}
