//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    
    public enum E_CMD_STATUS : int
    {
        Queue = 0,
        Sending = 1,
        Execution = 2,
        Aborting = 3,
        Canceling = 4,
        NormalEnd = 5,
        AbnormalEndByOHT = 6,
        AbnormalEndByMCS = 7,
        AbnormalEndByOHTC = 8,
        CancelEndByOHTC = 9
    }
}
