//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    
    public enum E_HIDQueueStatus : int
    {
        Request = 1,
        Blocking = 2,
        Thtough = 3,
        Release = 4,
        Abnormal_Release = 5
    }
}
