//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    
    public enum E_RAIL_TYPE : int
    {
        Straight_Horizontal = 0,
        Straight_Vertical = 1,
        Curve_0to90 = 2,
        Curve_90to180 = 3,
        Curve_180to270 = 4,
        Curve_270to360 = 5,
        Arrow_Up = 12,
        Arrow_Down = 13,
        Arrow_Left = 14,
        Arrow_Right = 15
    }
}
