//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortDef
    {
        public string StockerID { get; set; }
        public string PLCPortID { get; set; }
        public string OHBName { get; set; }
        public E_PORT_STATUS State { get; set; }
        public Nullable<decimal> Stage { get; set; }
        public Nullable<E_PORT_STATUS> AGVState { get; set; }
        public string UnitType { get; set; }
        public string HostEQPortID { get; set; }
        public string ShelfID { get; set; }
        public E_PortType PortType { get; set; }
        public Nullable<decimal> PortLocationType { get; set; }
        public Nullable<decimal> PortTypeIndex { get; set; }
        public Nullable<decimal> SourceWeighted { get; set; }
        public Nullable<decimal> DestWeighted { get; set; }
        public Nullable<decimal> Direction { get; set; }
        public Nullable<decimal> Color { get; set; }
        public Nullable<decimal> TimeOutForAutoUD { get; set; }
        public string TimeOutForAutoInZone { get; set; }
        public string AlternateToZone { get; set; }
        public Nullable<decimal> Vehicles { get; set; }
        public Nullable<decimal> Floor { get; set; }
        public string IgnoreModeChange { get; set; }
        public string ReportMCSFlag { get; set; }
        public Nullable<decimal> ReportStage { get; set; }
        public Nullable<decimal> NetHStnNo { get; set; }
        public Nullable<decimal> AreaSensorStnNo { get; set; }
        public string Presenton_InsCST { get; set; }
        public string Presentoff_DelCST { get; set; }
        public string ToEQ { get; set; }
        public string TrnDT { get; set; }
        public Nullable<decimal> AlarmType { get; set; }
        public string ADR_ID { get; set; }
        public Nullable<E_PortType> PortTypeDef { get; set; }
        public int PRIORITY { get; set; }
        public string ZoneName { get; set; }
    }
}
