//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCALE_BASE_DATA
    {
        public int RESOLUTION { get; set; }
        public int INPOSITION_AREA { get; set; }
        public int INPOSITION_STABLE_TIME { get; set; }
        public int TOTAL_SCALE_PULSE { get; set; }
        public int SCALE_OFFSET { get; set; }
        public int SCALE_RESE_DIST { get; set; }
        public E_DIRC_DRIV READ_DIR { get; set; }
        public string SUB_VER { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string ADD_USER { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string UPD_USER { get; set; }
    }
}
