//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShelfDef
    {
        public string StockerID { get; set; }
        public string ShelfID { get; set; }
        public decimal Stage { get; set; }
        public string Bank_X { get; set; }
        public string Bay_Y { get; set; }
        public string Level_Z { get; set; }
        public Nullable<decimal> LocateCraneNo { get; set; }
        public Nullable<decimal> ShelfType { get; set; }
        public string ShelfState { get; set; }
        public string ZoneID { get; set; }
        public string Enable { get; set; }
        public string OldEnableSts { get; set; }
        public string EmptyBlockFlag { get; set; }
        public Nullable<decimal> HoldState { get; set; }
        public string BCRReadFlag { get; set; }
        public Nullable<decimal> TransferTimes { get; set; }
        public string ChargeLoc { get; set; }
        public Nullable<decimal> SelectPriority { get; set; }
        public string Remark { get; set; }
        public string TrnDT { get; set; }
        public Nullable<decimal> HandoffDirection { get; set; }
        public string ADR_ID { get; set; }
    }
}
