//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class UASUSR
    {
        public string USER_ID { get; set; }
        public string PASSWD { get; set; }
        public string BADGE_NUMBER { get; set; }
        public string USER_NAME { get; set; }
        public string DISABLE_FLG { get; set; }
        public string POWER_USER_FLG { get; set; }
        public string ADMIN_FLG { get; set; }
        public string USER_GRP { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
