//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHCMD_OHTC_MCS
    {
        public string CMD_ID_MCS { get; set; }
        public string VH_ID { get; set; }
        public string CARRIER_ID { get; set; }
        public string HOSTSOURCE { get; set; }
        public string HOSTDESTINATION { get; set; }
        public Nullable<System.DateTime> MCS_CMD_INSER_TIME { get; set; }
        public Nullable<System.DateTime> MCS_CMD_START_TIME { get; set; }
        public Nullable<System.DateTime> MCS_CMD_FINISH_TIME { get; set; }
        public Nullable<int> MCS_COMMANDSTATE { get; set; }
        public int OHTC_CMD_STATUS { get; set; }
        public int OHTC_CMD_TYPE { get; set; }
        public Nullable<System.DateTime> OHTC_CMD_START_TIME { get; set; }
        public Nullable<System.DateTime> OHTC_CMD_END_TIME { get; set; }
        public Nullable<int> OHTC_COMPLETE_STATUS { get; set; }
    }
}
