//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneDef
    {
        public string StockerID { get; set; }
        public string ZoneID { get; set; }
        public string ZoneName { get; set; }
        public Nullable<decimal> HighWaterMark { get; set; }
        public Nullable<decimal> LowWaterMark { get; set; }
        public Nullable<decimal> ZoneType { get; set; }
        public string InventoryCheck { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> SourceWeighted { get; set; }
        public Nullable<decimal> DestWeighted { get; set; }
        public string Remark { get; set; }
        public string TrnDT { get; set; }
    }
}
