--drop Index IHCMD_MCS ON HCMD_MCS;
create INDEX IHCMD_MCS ON HCMD_MCS(HOSTSOURCE,HOSTDESTINATION,CMD_INSER_TIME,CMD_START_TIME,CMD_FINISH_TIME,COMMANDSTATE,CMD_ID);


--drop Index IHCMD_OHTC ON HCMD_OHTC
create INDEX IHCMD_OHTC ON HCMD_OHTC(CMD_ID_MCS,VH_ID,CMD_STAUS,CMD_TPYE,COMPLETE_STATUS);


--DROP VIEW VHCMD_OHTC_MCS
Create VIEW VHCMD_OHTC_MCS 
As
Select  
ISNULL(sbOHTC.CMD_ID_MCS,'0') As CMD_ID_MCS,
sbOHTC.VH_ID As VH_ID,
sbOHTC.CARRIER_ID As CARRIER_ID,
sbMCS.HOSTSOURCE As HOSTSOURCE,
sbMCS.HOSTDESTINATION As HOSTDESTINATION,
sbMCS.CMD_INSER_TIME As MCS_CMD_INSER_TIME,
sbMCS.CMD_START_TIME As MCS_CMD_START_TIME,
sbMCS.CMD_FINISH_TIME As MCS_CMD_FINISH_TIME,
sbMCS.COMMANDSTATE As MCS_COMMANDSTATE,
sbOHTC.CMD_STAUS As OHTC_CMD_STATUS,
sbOHTC.CMD_TPYE As OHTC_CMD_TYPE,
sbOHTC.CMD_START_TIME As OHTC_CMD_START_TIME,
sbOHTC.CMD_END_TIME As OHTC_CMD_END_TIME,
sbOHTC.COMPLETE_STATUS As OHTC_COMPLETE_STATUS
From HCMD_OHTC sbOHTC
Left JOIN HCMD_MCS sbMCS on sbMCS.CMD_ID = sbOHTC.CMD_ID_MCS and sbMCS.CARRIER_ID = sbOHTC.CARRIER_ID